# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_organic_inner import SearchSerpDataDtoOrganicInner

class TestSearchSerpDataDtoOrganicInner(unittest.TestCase):
    """SearchSerpDataDtoOrganicInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoOrganicInner:
        """Test SearchSerpDataDtoOrganicInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoOrganicInner`
        """
        model = SearchSerpDataDtoOrganicInner()
        if include_optional:
            return SearchSerpDataDtoOrganicInner(
                link = 'https://recruiterflow.com/',
                source = 'Recruiterflow',
                display_link = 'https://recruiterflow.com',
                title = 'Recruiterflow - Best AI-Native ATS & CRM for Executive ...',
                description = 'Recruiterflow is the best AI-Native ATS & CRM software for executive search firms...',
                snippet_highlighted_words = [
                    ''
                    ],
                extensions = [
                    geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner.SearchSerpDataDto_organic_inner_extensions_inner(
                        inline = True, 
                        type = 'text', 
                        text = 'Jul 15, 2025', 
                        rank = 1.337, )
                    ],
                icon = '',
                rank = 1,
                global_rank = 1
            )
        else:
            return SearchSerpDataDtoOrganicInner(
        )
        """

    def testSearchSerpDataDtoOrganicInner(self):
        """Test SearchSerpDataDtoOrganicInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
