# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.load_time_response_dto import LoadTimeResponseDto

class TestLoadTimeResponseDto(unittest.TestCase):
    """LoadTimeResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadTimeResponseDto:
        """Test LoadTimeResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadTimeResponseDto`
        """
        model = LoadTimeResponseDto()
        if include_optional:
            return LoadTimeResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Site is reachable.',
                meta = geekflare_api.models.load_time_meta_dto.LoadTimeMetaDto(
                    url = 'https://example.com', 
                    proxy_country = 'us', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = geekflare_api.models.load_time_data_dto.LoadTimeDataDto(
                    dns = 10, 
                    connect = 12, 
                    tls = 9, 
                    send = 19, 
                    wait = 86, 
                    total = 88, 
                    status_code = 404, 
                    reason_phrase = 'Not Found', 
                    timings = null, 
                    network = null, 
                    headers = {server=cloudflare, content-type=text/html; charset=utf-8, cache-control=no-cache}, 
                    protocol_support = null, )
            )
        else:
            return LoadTimeResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.load_time_meta_dto.LoadTimeMetaDto(
                    url = 'https://example.com', 
                    proxy_country = 'us', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = geekflare_api.models.load_time_data_dto.LoadTimeDataDto(
                    dns = 10, 
                    connect = 12, 
                    tls = 9, 
                    send = 19, 
                    wait = 86, 
                    total = 88, 
                    status_code = 404, 
                    reason_phrase = 'Not Found', 
                    timings = null, 
                    network = null, 
                    headers = {server=cloudflare, content-type=text/html; charset=utf-8, cache-control=no-cache}, 
                    protocol_support = null, ),
        )
        """

    def testLoadTimeResponseDto(self):
        """Test LoadTimeResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
