# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_forward_secrecy_dto import TlsForwardSecrecyDto

class TestTlsForwardSecrecyDto(unittest.TestCase):
    """TlsForwardSecrecyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsForwardSecrecyDto:
        """Test TlsForwardSecrecyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsForwardSecrecyDto`
        """
        model = TlsForwardSecrecyDto()
        if include_optional:
            return TlsForwardSecrecyDto(
                negotiated_cipher = None,
                ephemeral_key_type = None,
                ephemeral_key_size = None
            )
        else:
            return TlsForwardSecrecyDto(
                negotiated_cipher = None,
                ephemeral_key_type = None,
                ephemeral_key_size = None,
        )
        """

    def testTlsForwardSecrecyDto(self):
        """Test TlsForwardSecrecyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
