# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.redirect_check_response_dto import RedirectCheckResponseDto

class TestRedirectCheckResponseDto(unittest.TestCase):
    """RedirectCheckResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RedirectCheckResponseDto:
        """Test RedirectCheckResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RedirectCheckResponseDto`
        """
        model = RedirectCheckResponseDto()
        if include_optional:
            return RedirectCheckResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.redirect_check_meta_dto.RedirectCheckMetaDto(
                    url = 'example.com', 
                    proxy_country = US, 
                    test = null, ),
                data = [
                    geekflare_api.models.redirect_hop_dto.RedirectHopDto(
                        url = 'http://example.com/', 
                        status = 301, 
                        headers = [{name=location, value=https://example.com/}, {name=date, value=Mon, 29 Aug 2022 07:17:31 GMT}], )
                    ]
            )
        else:
            return RedirectCheckResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.redirect_check_meta_dto.RedirectCheckMetaDto(
                    url = 'example.com', 
                    proxy_country = US, 
                    test = null, ),
                data = [
                    geekflare_api.models.redirect_hop_dto.RedirectHopDto(
                        url = 'http://example.com/', 
                        status = 301, 
                        headers = [{name=location, value=https://example.com/}, {name=date, value=Mon, 29 Aug 2022 07:17:31 GMT}], )
                    ],
        )
        """

    def testRedirectCheckResponseDto(self):
        """Test RedirectCheckResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
