# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_color_entry_dto import BrandColorEntryDto

class TestBrandColorEntryDto(unittest.TestCase):
    """BrandColorEntryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandColorEntryDto:
        """Test BrandColorEntryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandColorEntryDto`
        """
        model = BrandColorEntryDto()
        if include_optional:
            return BrandColorEntryDto(
                hex = '#635BFF',
                usage = 'primary'
            )
        else:
            return BrandColorEntryDto(
                hex = '#635BFF',
                usage = 'primary',
        )
        """

    def testBrandColorEntryDto(self):
        """Test BrandColorEntryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
