# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_dto import BrandDto

class TestBrandDto(unittest.TestCase):
    """BrandDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandDto:
        """Test BrandDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandDto`
        """
        model = BrandDto()
        if include_optional:
            return BrandDto(
                url = 'https://example.com',
                refresh = False,
                mode = 'standard'
            )
        else:
            return BrandDto(
                url = 'https://example.com',
        )
        """

    def testBrandDto(self):
        """Test BrandDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
