# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.mixed_content_response_dto import MixedContentResponseDto

class TestMixedContentResponseDto(unittest.TestCase):
    """MixedContentResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MixedContentResponseDto:
        """Test MixedContentResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MixedContentResponseDto`
        """
        model = MixedContentResponseDto()
        if include_optional:
            return MixedContentResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Mixed content(s) found.',
                meta = geekflare_api.models.mixed_content_meta_dto.MixedContentMetaDto(
                    url = 'https://example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = None
            )
        else:
            return MixedContentResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Mixed content(s) found.',
                meta = geekflare_api.models.mixed_content_meta_dto.MixedContentMetaDto(
                    url = 'https://example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = None,
        )
        """

    def testMixedContentResponseDto(self):
        """Test MixedContentResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
