# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.summary_ai_prompt_dto import SummaryAiPromptDto

class TestSummaryAiPromptDto(unittest.TestCase):
    """SummaryAiPromptDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SummaryAiPromptDto:
        """Test SummaryAiPromptDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SummaryAiPromptDto`
        """
        model = SummaryAiPromptDto()
        if include_optional:
            return SummaryAiPromptDto(
                type = 'prompt',
                style = 'paragraph',
                focus = 'pricing',
                max_length = 5
            )
        else:
            return SummaryAiPromptDto(
                type = 'prompt',
        )
        """

    def testSummaryAiPromptDto(self):
        """Test SummaryAiPromptDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
