# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.dns_sec_response_dto import DnsSecResponseDto

class TestDnsSecResponseDto(unittest.TestCase):
    """DnsSecResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsSecResponseDto:
        """Test DnsSecResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsSecResponseDto`
        """
        model = DnsSecResponseDto()
        if include_optional:
            return DnsSecResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.dns_sec_meta_dto.DnsSecMetaDto(
                    url = 'example.com', 
                    test = null, ),
                data = geekflare_api.models.dns_sec_data_dto.DnsSecDataDto(
                    is_enabled = True, 
                    dnskey = [DNSKEY 256 3 13 oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8 KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA==], 
                    rrsig = [RRSIG DNSKEY 13 2 3600 20251124121323 20250924121323 2371 geekflare.com. LUeqKWfw4GcaqSaCbFT7ik6mTgFdWsRdVzn1hHGSwMGZ4HuwlVFB3e1K 9Os+4DnxyYNkfWkBHJcBfFN7e4snHg==], )
            )
        else:
            return DnsSecResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.dns_sec_meta_dto.DnsSecMetaDto(
                    url = 'example.com', 
                    test = null, ),
                data = geekflare_api.models.dns_sec_data_dto.DnsSecDataDto(
                    is_enabled = True, 
                    dnskey = [DNSKEY 256 3 13 oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8 KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA==], 
                    rrsig = [RRSIG DNSKEY 13 2 3600 20251124121323 20250924121323 2371 geekflare.com. LUeqKWfw4GcaqSaCbFT7ik6mTgFdWsRdVzn1hHGSwMGZ4HuwlVFB3e1K 9Os+4DnxyYNkfWkBHJcBfFN7e4snHg==], ),
        )
        """

    def testDnsSecResponseDto(self):
        """Test DnsSecResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
