# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.default_extraction_field_dto import DefaultExtractionFieldDto

class TestDefaultExtractionFieldDto(unittest.TestCase):
    """DefaultExtractionFieldDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultExtractionFieldDto:
        """Test DefaultExtractionFieldDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultExtractionFieldDto`
        """
        model = DefaultExtractionFieldDto()
        if include_optional:
            return DefaultExtractionFieldDto(
                title = 'Product Name',
                value = Some hardcoded string
            )
        else:
            return DefaultExtractionFieldDto(
                title = 'Product Name',
                value = Some hardcoded string,
        )
        """

    def testDefaultExtractionFieldDto(self):
        """Test DefaultExtractionFieldDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
