# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_request_dto import SearchRequestDto

class TestSearchRequestDto(unittest.TestCase):
    """SearchRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchRequestDto:
        """Test SearchRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchRequestDto`
        """
        model = SearchRequestDto()
        if include_optional:
            return SearchRequestDto(
                query = 'best running shoes',
                limit = 10,
                time = 'any',
                location = 'us',
                source = 'web',
                category = 'general',
                include_domains = [reddit.com, stackoverflow.com],
                exclude_domains = [pinterest.com],
                format = 'json',
                scrape = False,
                scrape_limit = 3
            )
        else:
            return SearchRequestDto(
                query = 'best running shoes',
        )
        """

    def testSearchRequestDto(self):
        """Test SearchRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
