# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.web_scrape_dto_ai_prompt import WebScrapeDtoAiPrompt

class TestWebScrapeDtoAiPrompt(unittest.TestCase):
    """WebScrapeDtoAiPrompt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebScrapeDtoAiPrompt:
        """Test WebScrapeDtoAiPrompt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebScrapeDtoAiPrompt`
        """
        model = WebScrapeDtoAiPrompt()
        if include_optional:
            return WebScrapeDtoAiPrompt(
                type = 'prompt',
                query = 'What is the return policy?',
                var_schema = {type=object, properties={title={type=string}, price={type=number}}},
                item_schema = {type=object, properties={name={type=string}, price={type=number}}},
                max_items = 20,
                style = 'paragraph',
                focus = 'pricing',
                max_length = 5,
                aspects = [sound quality, battery life, comfort, price],
                max_keywords = 10,
                include_entities = True
            )
        else:
            return WebScrapeDtoAiPrompt(
                type = 'prompt',
                query = 'What is the return policy?',
                var_schema = {type=object, properties={title={type=string}, price={type=number}}},
                item_schema = {type=object, properties={name={type=string}, price={type=number}}},
        )
        """

    def testWebScrapeDtoAiPrompt(self):
        """Test WebScrapeDtoAiPrompt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
