# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.open_port_response_dto import OpenPortResponseDto

class TestOpenPortResponseDto(unittest.TestCase):
    """OpenPortResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenPortResponseDto:
        """Test OpenPortResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenPortResponseDto`
        """
        model = OpenPortResponseDto()
        if include_optional:
            return OpenPortResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.open_port_meta_dto.OpenPortMetaDto(
                    url = 'https://example.com', 
                    top_ports = 100, 
                    port_ranges = '80,443,1000-1010', 
                    test = null, ),
                data = [
                    1.337
                    ]
            )
        else:
            return OpenPortResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.open_port_meta_dto.OpenPortMetaDto(
                    url = 'https://example.com', 
                    top_ports = 100, 
                    port_ranges = '80,443,1000-1010', 
                    test = null, ),
                data = [
                    1.337
                    ],
        )
        """

    def testOpenPortResponseDto(self):
        """Test OpenPortResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
