# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.mtr_response_dto import MtrResponseDto

class TestMtrResponseDto(unittest.TestCase):
    """MtrResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MtrResponseDto:
        """Test MtrResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MtrResponseDto`
        """
        model = MtrResponseDto()
        if include_optional:
            return MtrResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.mtr_meta_dto.MtrMetaDto(
                    url = 'example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = [{hop=1, host=240.192.18.19, asn=AS???, loss=0, sent=2, last=0.28, avg=0.29, best=0.28, worst=0.3, stdDev=0.01}, {hop=2, host=240.0.60.49, asn=AS???, loss=0, sent=2, last=0.28, avg=0.29, best=0.28, worst=0.29, stdDev=0.01}]
            )
        else:
            return MtrResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.mtr_meta_dto.MtrMetaDto(
                    url = 'example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                data = [{hop=1, host=240.192.18.19, asn=AS???, loss=0, sent=2, last=0.28, avg=0.29, best=0.28, worst=0.3, stdDev=0.01}, {hop=2, host=240.0.60.49, asn=AS???, loss=0, sent=2, last=0.28, avg=0.29, best=0.28, worst=0.29, stdDev=0.01}],
        )
        """

    def testMtrResponseDto(self):
        """Test MtrResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
