# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.load_time_multi_location_response_dto import LoadTimeMultiLocationResponseDto

class TestLoadTimeMultiLocationResponseDto(unittest.TestCase):
    """LoadTimeMultiLocationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadTimeMultiLocationResponseDto:
        """Test LoadTimeMultiLocationResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadTimeMultiLocationResponseDto`
        """
        model = LoadTimeMultiLocationResponseDto()
        if include_optional:
            return LoadTimeMultiLocationResponseDto(
                timestamp = 1787223157468,
                api_status = 'success',
                api_code = 200,
                message = 'Reachable from all 3 tested locations.',
                meta = geekflare_api.models.load_time_multi_location_meta_dto.LoadTimeMultiLocationMetaDto(
                    url = 'https://logi.com', 
                    test = null, 
                    target_countries = [us, gb, ca], 
                    follow_redirect = True, ),
                summary = geekflare_api.models.load_time_multi_location_response_dto_summary.LoadTimeMultiLocationResponseDto_summary(
                    reachable = [us, gb, ca], ),
                locations = [
                    geekflare_api.models.load_time_location_result_dto.LoadTimeLocationResultDto(
                        location = 'gb', 
                        country_name = 'Great Britain', 
                        status = 'reachable', 
                        data = { }, )
                    ]
            )
        else:
            return LoadTimeMultiLocationResponseDto(
                timestamp = 1787223157468,
                api_status = 'success',
                api_code = 200,
                message = 'Reachable from all 3 tested locations.',
                meta = geekflare_api.models.load_time_multi_location_meta_dto.LoadTimeMultiLocationMetaDto(
                    url = 'https://logi.com', 
                    test = null, 
                    target_countries = [us, gb, ca], 
                    follow_redirect = True, ),
                summary = geekflare_api.models.load_time_multi_location_response_dto_summary.LoadTimeMultiLocationResponseDto_summary(
                    reachable = [us, gb, ca], ),
                locations = [
                    geekflare_api.models.load_time_location_result_dto.LoadTimeLocationResultDto(
                        location = 'gb', 
                        country_name = 'Great Britain', 
                        status = 'reachable', 
                        data = { }, )
                    ],
        )
        """

    def testLoadTimeMultiLocationResponseDto(self):
        """Test LoadTimeMultiLocationResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
