# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.lighthouse_dto import LighthouseDto

class TestLighthouseDto(unittest.TestCase):
    """LighthouseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LighthouseDto:
        """Test LighthouseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LighthouseDto`
        """
        model = LighthouseDto()
        if include_optional:
            return LighthouseDto(
                url = 'https://example.com',
                device = 'desktop',
                follow_redirect = False,
                proxy_country = 'us',
                parameters = [--only-categories=seo]
            )
        else:
            return LighthouseDto(
                url = 'https://example.com',
        )
        """

    def testLighthouseDto(self):
        """Test LighthouseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
