# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_certificate_chain_dto import TlsCertificateChainDto

class TestTlsCertificateChainDto(unittest.TestCase):
    """TlsCertificateChainDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsCertificateChainDto:
        """Test TlsCertificateChainDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsCertificateChainDto`
        """
        model = TlsCertificateChainDto()
        if include_optional:
            return TlsCertificateChainDto(
                length = 1.337,
                complete = True,
                certificates = [
                    geekflare_api.models.tls_certificate_chain_entry_dto.TlsCertificateChainEntryDto(
                        common_name = '', 
                        issuer_common_name = '', 
                        fingerprint = '', )
                    ]
            )
        else:
            return TlsCertificateChainDto(
                length = 1.337,
                complete = True,
                certificates = [
                    geekflare_api.models.tls_certificate_chain_entry_dto.TlsCertificateChainEntryDto(
                        common_name = '', 
                        issuer_common_name = '', 
                        fingerprint = '', )
                    ],
        )
        """

    def testTlsCertificateChainDto(self):
        """Test TlsCertificateChainDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
