# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_vulnerabilities_dto import TlsVulnerabilitiesDto

class TestTlsVulnerabilitiesDto(unittest.TestCase):
    """TlsVulnerabilitiesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsVulnerabilitiesDto:
        """Test TlsVulnerabilitiesDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsVulnerabilitiesDto`
        """
        model = TlsVulnerabilitiesDto()
        if include_optional:
            return TlsVulnerabilitiesDto(
                poodle = None,
                drown = None,
                freak = None,
                logjam = None,
                sweet32 = None,
                rc4 = None,
                null_cipher = None,
                anonymous_cipher = None,
                crime = None
            )
        else:
            return TlsVulnerabilitiesDto(
                poodle = None,
                drown = None,
                freak = None,
                logjam = None,
                sweet32 = None,
                rc4 = None,
                null_cipher = None,
                anonymous_cipher = None,
                crime = None,
        )
        """

    def testTlsVulnerabilitiesDto(self):
        """Test TlsVulnerabilitiesDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
