# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.mtr_data_dto import MtrDataDto

class TestMtrDataDto(unittest.TestCase):
    """MtrDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MtrDataDto:
        """Test MtrDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MtrDataDto`
        """
        model = MtrDataDto()
        if include_optional:
            return MtrDataDto(
                hop = 1,
                host = '240.192.18.19',
                asn = 'AS???',
                loss = 0,
                sent = 2,
                last = 0.28,
                avg = 0.29,
                best = 0.28,
                worst = 0.3,
                std_dev = 0.01
            )
        else:
            return MtrDataDto(
                hop = 1,
                host = '240.192.18.19',
                asn = 'AS???',
                loss = 0,
                sent = 2,
                last = 0.28,
                avg = 0.29,
                best = 0.28,
                worst = 0.3,
                std_dev = 0.01,
        )
        """

    def testMtrDataDto(self):
        """Test MtrDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
