# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.base_error_response_dto import BaseErrorResponseDto

class TestBaseErrorResponseDto(unittest.TestCase):
    """BaseErrorResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseErrorResponseDto:
        """Test BaseErrorResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseErrorResponseDto`
        """
        model = BaseErrorResponseDto()
        if include_optional:
            return BaseErrorResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Invalid URL provided',
                details = 'The URL must be a valid HTTP or HTTPS URL'
            )
        else:
            return BaseErrorResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Invalid URL provided',
        )
        """

    def testBaseErrorResponseDto(self):
        """Test BaseErrorResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
