# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.url2_pdf_dto import Url2PdfDto

class TestUrl2PdfDto(unittest.TestCase):
    """Url2PdfDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Url2PdfDto:
        """Test Url2PdfDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Url2PdfDto`
        """
        model = Url2PdfDto()
        if include_optional:
            return Url2PdfDto(
                url = 'https://example.com',
                device = 'desktop',
                proxy_country = 'us',
                format = 'a4',
                orientation = 'portrait',
                margin = geekflare_api.models.margin_dto.MarginDto(
                    top = 25.4, 
                    bottom = 25.4, 
                    right = 25.4, 
                    left = 25.4, ),
                scale = 1.5,
                hide_cookie = False,
                skip_captcha = False,
                add_timestamp = False
            )
        else:
            return Url2PdfDto(
                url = 'https://example.com',
        )
        """

    def testUrl2PdfDto(self):
        """Test Url2PdfDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
