# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_data_dto import BrandDataDto

class TestBrandDataDto(unittest.TestCase):
    """BrandDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandDataDto:
        """Test BrandDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandDataDto`
        """
        model = BrandDataDto()
        if include_optional:
            return BrandDataDto(
                domain = 'stripe.com',
                name = '',
                tagline = '',
                description = '',
                slogan = '',
                is_nsfw = True,
                favicon = '',
                banner_url = '',
                logos = [
                    geekflare_api.models.brand_logo_dto.BrandLogoDto(
                        type = 'logo', 
                        theme = 'light', 
                        url = '', 
                        format = 'svg', )
                    ],
                colors = geekflare_api.models.brand_colors_dto.BrandColorsDto(
                    primary = '', 
                    secondary = '', 
                    background = '', 
                    text = '', 
                    accent = '', 
                    link = '', 
                    palette = [
                        geekflare_api.models.brand_color_entry_dto.BrandColorEntryDto(
                            hex = '#635BFF', 
                            usage = 'primary', )
                        ], ),
                color_scheme = 'light',
                fonts = [
                    geekflare_api.models.brand_font_dto.BrandFontDto(
                        family = '', 
                        usage = 'heading', 
                        source = 'custom', )
                    ],
                font_sizes = geekflare_api.models.brand_typography_dto.BrandTypographyDto(
                    h1 = '', 
                    h2 = '', 
                    body = '', ),
                components = geekflare_api.models.brand_components_dto.BrandComponentsDto(
                    button_primary = geekflare_api.models.brand_button_style_dto.BrandButtonStyleDto(
                        background = '', 
                        text_color = '', 
                        border_color = '', 
                        border_radius = '', 
                        shadow = '', ), 
                    button_secondary = geekflare_api.models.brand_button_style_dto.BrandButtonStyleDto(
                        background = '', 
                        text_color = '', 
                        border_color = '', 
                        border_radius = '', 
                        shadow = '', ), 
                    input = , ),
                spacing = geekflare_api.models.brand_spacing_dto.BrandSpacingDto(
                    base_unit = 1.337, 
                    border_radius = '', ),
                social_profiles = [
                    geekflare_api.models.brand_social_profile_dto.BrandSocialProfileDto(
                        name = 'twitter', 
                        url = '', )
                    ],
                links = geekflare_api.models.brand_links_dto.BrandLinksDto(
                    blog = '', 
                    login = '', 
                    signup = '', 
                    careers = '', 
                    contact = '', 
                    privacy = '', 
                    terms = '', 
                    pricing = '', ),
                company = geekflare_api.models.brand_company_dto.BrandCompanyDto(
                    founded_year = 2012, 
                    employees_range = '1-10', 
                    revenue_range = '<$1M', 
                    kind = 'PRIVATELY_HELD', 
                    industry = 'Business/Productivity Software', 
                    location = geekflare_api.models.brand_location_dto.BrandLocationDto(
                        city = geekflare_api.models.city.city(), 
                        state = geekflare_api.models.state.state(), 
                        country = geekflare_api.models.country.country(), 
                        country_code = geekflare_api.models.country_code.countryCode(), ), 
                    stock_ticker = 'NASDAQ:DBX', 
                    summary = '', 
                    target_audience = '', 
                    target_audience_segments = [
                        'Freelancers'
                        ], 
                    brand_voice = [
                        ''
                        ], 
                    use_cases = [
                        ''
                        ], ),
                page_meta = geekflare_api.models.brand_page_meta_dto.BrandPageMetaDto(
                    title = '', 
                    theme_color = '', 
                    canonical_url = '', 
                    language = '', 
                    og:url = '', 
                    og:type = '', 
                    og:title = '', 
                    og:description = '', 
                    og:image = '', 
                    og:image:type = '', 
                    og:image:width = '', 
                    og:image:height = '', 
                    og:site_name = '', 
                    og:locale = '', 
                    twitter:card = '', 
                    twitter:site = '', )
            )
        else:
            return BrandDataDto(
                domain = 'stripe.com',
        )
        """

    def testBrandDataDto(self):
        """Test BrandDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
