# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner import SearchSerpDataDtoOrganicInnerExtensionsInner

class TestSearchSerpDataDtoOrganicInnerExtensionsInner(unittest.TestCase):
    """SearchSerpDataDtoOrganicInnerExtensionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoOrganicInnerExtensionsInner:
        """Test SearchSerpDataDtoOrganicInnerExtensionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoOrganicInnerExtensionsInner`
        """
        model = SearchSerpDataDtoOrganicInnerExtensionsInner()
        if include_optional:
            return SearchSerpDataDtoOrganicInnerExtensionsInner(
                inline = True,
                type = 'text',
                text = 'Jul 15, 2025',
                rank = 1.337
            )
        else:
            return SearchSerpDataDtoOrganicInnerExtensionsInner(
        )
        """

    def testSearchSerpDataDtoOrganicInnerExtensionsInner(self):
        """Test SearchSerpDataDtoOrganicInnerExtensionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
