# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.image_search_response_dto import ImageSearchResponseDto

class TestImageSearchResponseDto(unittest.TestCase):
    """ImageSearchResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageSearchResponseDto:
        """Test ImageSearchResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageSearchResponseDto`
        """
        model = ImageSearchResponseDto()
        if include_optional:
            return ImageSearchResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = [
                    geekflare_api.models.image_search_result_item_dto.ImageSearchResultItemDto(
                        title = 'Nike Alphafly 3', 
                        image_url = 'https://example.com/img.jpg', 
                        source_url = 'https://example.com/page', 
                        width = 1024, 
                        height = 768, )
                    ]
            )
        else:
            return ImageSearchResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = [
                    geekflare_api.models.image_search_result_item_dto.ImageSearchResultItemDto(
                        title = 'Nike Alphafly 3', 
                        image_url = 'https://example.com/img.jpg', 
                        source_url = 'https://example.com/page', 
                        width = 1024, 
                        height = 768, )
                    ],
        )
        """

    def testImageSearchResponseDto(self):
        """Test ImageSearchResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
