# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_input import SearchSerpDataDtoInput

class TestSearchSerpDataDtoInput(unittest.TestCase):
    """SearchSerpDataDtoInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoInput:
        """Test SearchSerpDataDtoInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoInput`
        """
        model = SearchSerpDataDtoInput()
        if include_optional:
            return SearchSerpDataDtoInput(
                original_url = 'https://www.google.com/search?q=ats%20for%20agencies&gl=us',
                request_id = 'hl_309dd1bd_fawunsu8b5k'
            )
        else:
            return SearchSerpDataDtoInput(
        )
        """

    def testSearchSerpDataDtoInput(self):
        """Test SearchSerpDataDtoInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
