# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_certificate_dto import TlsCertificateDto

class TestTlsCertificateDto(unittest.TestCase):
    """TlsCertificateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsCertificateDto:
        """Test TlsCertificateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsCertificateDto`
        """
        model = TlsCertificateDto()
        if include_optional:
            return TlsCertificateDto(
                common_name = 'sni.cloudflaressl.com',
                subject_alt_name = 'DNS:*.example.com, DNS:sni.cloudflaressl.com, DNS:example.com',
                issuer = geekflare_api.models.tls_certificate_issuer_dto.TlsCertificateIssuerDto(
                    country = 'US', 
                    organization = 'Cloudflare, Inc.', 
                    common_name = 'Cloudflare Inc ECC CA-3', ),
                expiry = 'Jun  6 23:59:59 2023 GMT'
            )
        else:
            return TlsCertificateDto(
                common_name = 'sni.cloudflaressl.com',
                subject_alt_name = 'DNS:*.example.com, DNS:sni.cloudflaressl.com, DNS:example.com',
                issuer = geekflare_api.models.tls_certificate_issuer_dto.TlsCertificateIssuerDto(
                    country = 'US', 
                    organization = 'Cloudflare, Inc.', 
                    common_name = 'Cloudflare Inc ECC CA-3', ),
                expiry = 'Jun  6 23:59:59 2023 GMT',
        )
        """

    def testTlsCertificateDto(self):
        """Test TlsCertificateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
