# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_people_also_ask_inner import SearchSerpDataDtoPeopleAlsoAskInner

class TestSearchSerpDataDtoPeopleAlsoAskInner(unittest.TestCase):
    """SearchSerpDataDtoPeopleAlsoAskInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoPeopleAlsoAskInner:
        """Test SearchSerpDataDtoPeopleAlsoAskInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoPeopleAlsoAskInner`
        """
        model = SearchSerpDataDtoPeopleAlsoAskInner()
        if include_optional:
            return SearchSerpDataDtoPeopleAlsoAskInner(
                question = 'What is the best ATS for recruiting agencies?',
                question_link = '',
                question_type = 'ai_overview',
                rank = 1,
                global_rank = 1
            )
        else:
            return SearchSerpDataDtoPeopleAlsoAskInner(
        )
        """

    def testSearchSerpDataDtoPeopleAlsoAskInner(self):
        """Test SearchSerpDataDtoPeopleAlsoAskInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
