# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.grounded_answer_response_dto import GroundedAnswerResponseDto

class TestGroundedAnswerResponseDto(unittest.TestCase):
    """GroundedAnswerResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroundedAnswerResponseDto:
        """Test GroundedAnswerResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroundedAnswerResponseDto`
        """
        model = GroundedAnswerResponseDto()
        if include_optional:
            return GroundedAnswerResponseDto(
                timestamp = 1783063255117,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = geekflare_api.models.grounded_answer_data_dto.GroundedAnswerDataDto(
                    answer = '', 
                    sources = [
                        geekflare_api.models.grounded_source_dto.GroundedSourceDto(
                            title = 'web', 
                            url = 'https://example.com', 
                            position = 1, )
                        ], )
            )
        else:
            return GroundedAnswerResponseDto(
                timestamp = 1783063255117,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = geekflare_api.models.grounded_answer_data_dto.GroundedAnswerDataDto(
                    answer = '', 
                    sources = [
                        geekflare_api.models.grounded_source_dto.GroundedSourceDto(
                            title = 'web', 
                            url = 'https://example.com', 
                            position = 1, )
                        ], ),
        )
        """

    def testGroundedAnswerResponseDto(self):
        """Test GroundedAnswerResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
