# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_general import SearchSerpDataDtoGeneral

class TestSearchSerpDataDtoGeneral(unittest.TestCase):
    """SearchSerpDataDtoGeneral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoGeneral:
        """Test SearchSerpDataDtoGeneral
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoGeneral`
        """
        model = SearchSerpDataDtoGeneral()
        if include_optional:
            return SearchSerpDataDtoGeneral(
                search_engine = 'google',
                query = 'ats for agencies',
                detected_query = 'ats for agencies',
                results_cnt = 128,
                search_time = 0.24,
                language = 'en',
                country_code = 'US',
                location = 'United States',
                gl = 'US',
                mobile = False,
                basic_view = False,
                search_type = 'text',
                page_title = 'ats for agencies - Google Search',
                timestamp = '2026-09-29T16:22:20.881Z'
            )
        else:
            return SearchSerpDataDtoGeneral(
        )
        """

    def testSearchSerpDataDtoGeneral(self):
        """Test SearchSerpDataDtoGeneral"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
