# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.screenshot_dto import ScreenshotDto

class TestScreenshotDto(unittest.TestCase):
    """ScreenshotDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScreenshotDto:
        """Test ScreenshotDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScreenshotDto`
        """
        model = ScreenshotDto()
        if include_optional:
            return ScreenshotDto(
                url = 'https://example.com',
                device = 'desktop',
                proxy_country = 'us',
                type = 'png',
                full_page = True,
                block_ads = True,
                hide_cookie = True,
                skip_captcha = True,
                add_timestamp = True,
                page_height = 2000,
                viewport_width = 1280,
                viewport_height = 800,
                theme = 'auto',
                remove_background = False,
                highlight_links = False,
                delay = 2,
                disable_animations = False,
                quality = 90,
                scale_factor = 1,
                capture_beyond_viewport = True
            )
        else:
            return ScreenshotDto(
                url = 'https://example.com',
        )
        """

    def testScreenshotDto(self):
        """Test ScreenshotDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
