# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_pagination import SearchSerpDataDtoPagination

class TestSearchSerpDataDtoPagination(unittest.TestCase):
    """SearchSerpDataDtoPagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoPagination:
        """Test SearchSerpDataDtoPagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoPagination`
        """
        model = SearchSerpDataDtoPagination()
        if include_optional:
            return SearchSerpDataDtoPagination(
                pages = [
                    geekflare_api.models.search_serp_data_dto_pagination_pages_inner.SearchSerpDataDto_pagination_pages_inner(
                        page = 2, 
                        start = 10, 
                        link = '', )
                    ],
                current_page = 1,
                next_page = 2,
                next_page_start = 10,
                next_page_link = ''
            )
        else:
            return SearchSerpDataDtoPagination(
        )
        """

    def testSearchSerpDataDtoPagination(self):
        """Test SearchSerpDataDtoPagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
