# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_ai_overview import SearchSerpDataDtoAiOverview

class TestSearchSerpDataDtoAiOverview(unittest.TestCase):
    """SearchSerpDataDtoAiOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoAiOverview:
        """Test SearchSerpDataDtoAiOverview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoAiOverview`
        """
        model = SearchSerpDataDtoAiOverview()
        if include_optional:
            return SearchSerpDataDtoAiOverview(
                text = '',
                html = '',
                references = [
                    geekflare_api.models.search_serp_data_dto_ai_overview_references_inner.SearchSerpDataDto_ai_overview_references_inner(
                        title = 'The Best Laptops Under $1,000 We've Tested for 2026 | PCMag', 
                        url = 'https://www.pcmag.com/picks/best-laptops-under-1000', 
                        source = 'PCMag', 
                        snippet = '', )
                    ]
            )
        else:
            return SearchSerpDataDtoAiOverview(
        )
        """

    def testSearchSerpDataDtoAiOverview(self):
        """Test SearchSerpDataDtoAiOverview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
