# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.detected_service_dto import DetectedServiceDto

class TestDetectedServiceDto(unittest.TestCase):
    """DetectedServiceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetectedServiceDto:
        """Test DetectedServiceDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetectedServiceDto`
        """
        model = DetectedServiceDto()
        if include_optional:
            return DetectedServiceDto(
                name = ssh,
                product = OpenSSH,
                version = 8.9p1,
                extra_info = Ubuntu Linux; protocol 2.0,
                os_type = Linux
            )
        else:
            return DetectedServiceDto(
        )
        """

    def testDetectedServiceDto(self):
        """Test DetectedServiceDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
