# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.dns_record_response_dto import DnsRecordResponseDto

class TestDnsRecordResponseDto(unittest.TestCase):
    """DnsRecordResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsRecordResponseDto:
        """Test DnsRecordResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsRecordResponseDto`
        """
        model = DnsRecordResponseDto()
        if include_optional:
            return DnsRecordResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.dns_meta_dto.DnsMetaDto(
                    url = 'https://example.com', 
                    types = '[A, MX]', 
                    test = null, ),
                data = {A=[172.67.70.213, 104.26.11.88, 104.26.10.88], MX=[{exchange=alt3.aspmx.l.google.com, priority=10}, {exchange=aspmx.l.google.com, priority=1}]}
            )
        else:
            return DnsRecordResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.dns_meta_dto.DnsMetaDto(
                    url = 'https://example.com', 
                    types = '[A, MX]', 
                    test = null, ),
                data = {A=[172.67.70.213, 104.26.11.88, 104.26.10.88], MX=[{exchange=alt3.aspmx.l.google.com, priority=10}, {exchange=aspmx.l.google.com, priority=1}]},
        )
        """

    def testDnsRecordResponseDto(self):
        """Test DnsRecordResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
