# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.web_scrape_dto_proxy_mode import WebScrapeDtoProxyMode

class TestWebScrapeDtoProxyMode(unittest.TestCase):
    """WebScrapeDtoProxyMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebScrapeDtoProxyMode:
        """Test WebScrapeDtoProxyMode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebScrapeDtoProxyMode`
        """
        model = WebScrapeDtoProxyMode()
        if include_optional:
            return WebScrapeDtoProxyMode(
            )
        else:
            return WebScrapeDtoProxyMode(
        )
        """

    def testWebScrapeDtoProxyMode(self):
        """Test WebScrapeDtoProxyMode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
