# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.margin_dto import MarginDto

class TestMarginDto(unittest.TestCase):
    """MarginDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarginDto:
        """Test MarginDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarginDto`
        """
        model = MarginDto()
        if include_optional:
            return MarginDto(
                top = 25.4,
                bottom = 25.4,
                right = 25.4,
                left = 25.4
            )
        else:
            return MarginDto(
        )
        """

    def testMarginDto(self):
        """Test MarginDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
