# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.timings_dto import TimingsDto

class TestTimingsDto(unittest.TestCase):
    """TimingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimingsDto:
        """Test TimingsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimingsDto`
        """
        model = TimingsDto()
        if include_optional:
            return TimingsDto(
                dns = 21,
                connect = 15,
                tls = 40,
                send = 1,
                wait = 457,
                ttfb = 534,
                download = 4,
                total = 538,
                redirect_duration = 0
            )
        else:
            return TimingsDto(
                dns = 21,
                connect = 15,
                tls = 40,
                send = 1,
                wait = 457,
                ttfb = 534,
                download = 4,
                total = 538,
                redirect_duration = 0,
        )
        """

    def testTimingsDto(self):
        """Test TimingsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
