# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_certificate_issuer_dto import TlsCertificateIssuerDto

class TestTlsCertificateIssuerDto(unittest.TestCase):
    """TlsCertificateIssuerDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsCertificateIssuerDto:
        """Test TlsCertificateIssuerDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsCertificateIssuerDto`
        """
        model = TlsCertificateIssuerDto()
        if include_optional:
            return TlsCertificateIssuerDto(
                country = 'US',
                organization = 'Cloudflare, Inc.',
                common_name = 'Cloudflare Inc ECC CA-3'
            )
        else:
            return TlsCertificateIssuerDto(
                country = 'US',
                organization = 'Cloudflare, Inc.',
                common_name = 'Cloudflare Inc ECC CA-3',
        )
        """

    def testTlsCertificateIssuerDto(self):
        """Test TlsCertificateIssuerDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
