# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_meta_dto import SearchMetaDto

class TestSearchMetaDto(unittest.TestCase):
    """SearchMetaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchMetaDto:
        """Test SearchMetaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchMetaDto`
        """
        model = SearchMetaDto()
        if include_optional:
            return SearchMetaDto(
                query = 'best running shoes',
                count = 10,
                source = web,
                location = 'us',
                time = 'd',
                scrape = False,
                scrape_limit = 3,
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', )
            )
        else:
            return SearchMetaDto(
                query = 'best running shoes',
                count = 10,
                source = web,
                location = 'us',
                time = 'd',
                scrape = False,
                scrape_limit = 3,
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', ),
        )
        """

    def testSearchMetaDto(self):
        """Test SearchMetaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
