# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.screenshot_response_dto import ScreenshotResponseDto

class TestScreenshotResponseDto(unittest.TestCase):
    """ScreenshotResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScreenshotResponseDto:
        """Test ScreenshotResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScreenshotResponseDto`
        """
        model = ScreenshotResponseDto()
        if include_optional:
            return ScreenshotResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.screenshot_meta_dto.ScreenshotMetaDto(
                    url = 'https://example.com', 
                    type = 'png', 
                    device = 'desktop', 
                    full_page = False, 
                    block_ads = False, 
                    hide_cookie = False, 
                    skip_captcha = False, 
                    add_timestamp = False, 
                    proxy_country = '', 
                    page_height = 2000, 
                    viewport_width = 1280, 
                    viewport_height = 800, 
                    theme = 'auto', 
                    remove_background = False, 
                    highlight_links = False, 
                    delay = 2, 
                    disable_animations = False, 
                    quality = 90, 
                    scale_factor = 1, 
                    capture_beyond_viewport = True, 
                    test = null, ),
                data = 'https://geekflare.com/tests/screenshot/kbi6d206g87ituahb7icwtpr.png'
            )
        else:
            return ScreenshotResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.screenshot_meta_dto.ScreenshotMetaDto(
                    url = 'https://example.com', 
                    type = 'png', 
                    device = 'desktop', 
                    full_page = False, 
                    block_ads = False, 
                    hide_cookie = False, 
                    skip_captcha = False, 
                    add_timestamp = False, 
                    proxy_country = '', 
                    page_height = 2000, 
                    viewport_width = 1280, 
                    viewport_height = 800, 
                    theme = 'auto', 
                    remove_background = False, 
                    highlight_links = False, 
                    delay = 2, 
                    disable_animations = False, 
                    quality = 90, 
                    scale_factor = 1, 
                    capture_beyond_viewport = True, 
                    test = null, ),
                data = 'https://geekflare.com/tests/screenshot/kbi6d206g87ituahb7icwtpr.png',
        )
        """

    def testScreenshotResponseDto(self):
        """Test ScreenshotResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
