# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.meta_scrape_meta_dto import MetaScrapeMetaDto

class TestMetaScrapeMetaDto(unittest.TestCase):
    """MetaScrapeMetaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetaScrapeMetaDto:
        """Test MetaScrapeMetaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetaScrapeMetaDto`
        """
        model = MetaScrapeMetaDto()
        if include_optional:
            return MetaScrapeMetaDto(
                url = 'https://example.com',
                device = 'desktop',
                format = 'json',
                file_output = False,
                block_ads = True,
                render_js = True,
                proxy_country = '',
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', )
            )
        else:
            return MetaScrapeMetaDto(
                url = 'https://example.com',
                device = 'desktop',
                format = 'json',
                file_output = False,
                block_ads = True,
                render_js = True,
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', ),
        )
        """

    def testMetaScrapeMetaDto(self):
        """Test MetaScrapeMetaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
