# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.load_time_data_dto import LoadTimeDataDto

class TestLoadTimeDataDto(unittest.TestCase):
    """LoadTimeDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadTimeDataDto:
        """Test LoadTimeDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadTimeDataDto`
        """
        model = LoadTimeDataDto()
        if include_optional:
            return LoadTimeDataDto(
                dns = 10,
                connect = 12,
                tls = 9,
                send = 19,
                wait = 86,
                total = 88,
                status_code = 404,
                reason_phrase = 'Not Found',
                timings = geekflare_api.models.timings_dto.TimingsDto(
                    dns = 21, 
                    connect = 15, 
                    tls = 40, 
                    send = 1, 
                    wait = 457, 
                    ttfb = 534, 
                    download = 4, 
                    total = 538, 
                    redirect_duration = 0, ),
                network = geekflare_api.models.network_dto.NetworkDto(
                    protocol = 'h2', 
                    remote_ip = '1.1.1.1', 
                    bytes_read = 15400, ),
                headers = {server=cloudflare, content-type=text/html; charset=utf-8, cache-control=no-cache},
                protocol_support = geekflare_api.models.protocol_support_dto.ProtocolSupportDto(
                    http10 = False, 
                    http11 = True, 
                    http2 = True, 
                    http3 = False, 
                    http3_supported_version = [h3-29, h3], )
            )
        else:
            return LoadTimeDataDto(
                dns = 10,
                connect = 12,
                tls = 9,
                send = 19,
                wait = 86,
                total = 88,
                status_code = 404,
                reason_phrase = 'Not Found',
                timings = geekflare_api.models.timings_dto.TimingsDto(
                    dns = 21, 
                    connect = 15, 
                    tls = 40, 
                    send = 1, 
                    wait = 457, 
                    ttfb = 534, 
                    download = 4, 
                    total = 538, 
                    redirect_duration = 0, ),
                network = geekflare_api.models.network_dto.NetworkDto(
                    protocol = 'h2', 
                    remote_ip = '1.1.1.1', 
                    bytes_read = 15400, ),
                headers = {server=cloudflare, content-type=text/html; charset=utf-8, cache-control=no-cache},
                protocol_support = geekflare_api.models.protocol_support_dto.ProtocolSupportDto(
                    http10 = False, 
                    http11 = True, 
                    http2 = True, 
                    http3 = False, 
                    http3_supported_version = [h3-29, h3], ),
        )
        """

    def testLoadTimeDataDto(self):
        """Test LoadTimeDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
