# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_scan_response_dto import TlsScanResponseDto

class TestTlsScanResponseDto(unittest.TestCase):
    """TlsScanResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsScanResponseDto:
        """Test TlsScanResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsScanResponseDto`
        """
        model = TlsScanResponseDto()
        if include_optional:
            return TlsScanResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.tls_scan_meta_dto.TlsScanMetaDto(
                    url = 'example.com', 
                    test = {id=40zt4but04y07ccn4pov5fiolzrxbxdg}, ),
                data = geekflare_api.models.tls_scan_data_dto.TlsScanDataDto(
                    protocols = null, 
                    certificate = null, )
            )
        else:
            return TlsScanResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.tls_scan_meta_dto.TlsScanMetaDto(
                    url = 'example.com', 
                    test = {id=40zt4but04y07ccn4pov5fiolzrxbxdg}, ),
                data = geekflare_api.models.tls_scan_data_dto.TlsScanDataDto(
                    protocols = null, 
                    certificate = null, ),
        )
        """

    def testTlsScanResponseDto(self):
        """Test TlsScanResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
