# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_meta_dto import BrandMetaDto

class TestBrandMetaDto(unittest.TestCase):
    """BrandMetaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandMetaDto:
        """Test BrandMetaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandMetaDto`
        """
        model = BrandMetaDto()
        if include_optional:
            return BrandMetaDto(
                domain = 'stripe.com',
                mode = 'standard',
                cached = True,
                last_updated = '2026-06-15T08:32:00Z',
                data_age = '5d',
                refresh_requested = False,
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', )
            )
        else:
            return BrandMetaDto(
                domain = 'stripe.com',
                mode = 'standard',
                cached = True,
                last_updated = '2026-06-15T08:32:00Z',
                data_age = '5d',
                refresh_requested = False,
                test = geekflare_api.models.test_meta_dto.TestMetaDto(
                    id = 'mxqx9v9y0742lap6altwdteqd28t23nq', ),
        )
        """

    def testBrandMetaDto(self):
        """Test BrandMetaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
