# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.meta_scrape_response_dto import MetaScrapeResponseDto

class TestMetaScrapeResponseDto(unittest.TestCase):
    """MetaScrapeResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetaScrapeResponseDto:
        """Test MetaScrapeResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetaScrapeResponseDto`
        """
        model = MetaScrapeResponseDto()
        if include_optional:
            return MetaScrapeResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.meta_scrape_meta_dto.MetaScrapeMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    format = 'json', 
                    file_output = False, 
                    block_ads = True, 
                    render_js = True, 
                    proxy_country = '', 
                    test = null, ),
                data = https://example.com/9bulgk075ed9m3vhua5vcrp0.html
            )
        else:
            return MetaScrapeResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.meta_scrape_meta_dto.MetaScrapeMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    format = 'json', 
                    file_output = False, 
                    block_ads = True, 
                    render_js = True, 
                    proxy_country = '', 
                    test = null, ),
                data = https://example.com/9bulgk075ed9m3vhua5vcrp0.html,
        )
        """

    def testMetaScrapeResponseDto(self):
        """Test MetaScrapeResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
