# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_ai_overview_references_inner import SearchSerpDataDtoAiOverviewReferencesInner

class TestSearchSerpDataDtoAiOverviewReferencesInner(unittest.TestCase):
    """SearchSerpDataDtoAiOverviewReferencesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoAiOverviewReferencesInner:
        """Test SearchSerpDataDtoAiOverviewReferencesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoAiOverviewReferencesInner`
        """
        model = SearchSerpDataDtoAiOverviewReferencesInner()
        if include_optional:
            return SearchSerpDataDtoAiOverviewReferencesInner(
                title = 'The Best Laptops Under $1,000 We've Tested for 2026 | PCMag',
                url = 'https://www.pcmag.com/picks/best-laptops-under-1000',
                source = 'PCMag',
                snippet = ''
            )
        else:
            return SearchSerpDataDtoAiOverviewReferencesInner(
        )
        """

    def testSearchSerpDataDtoAiOverviewReferencesInner(self):
        """Test SearchSerpDataDtoAiOverviewReferencesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
