# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.broken_link_summary_dto import BrokenLinkSummaryDto

class TestBrokenLinkSummaryDto(unittest.TestCase):
    """BrokenLinkSummaryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrokenLinkSummaryDto:
        """Test BrokenLinkSummaryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrokenLinkSummaryDto`
        """
        model = BrokenLinkSummaryDto()
        if include_optional:
            return BrokenLinkSummaryDto(
                total = 5,
                successful = 2,
                redirects = 2,
                broken = 1,
                server_error = 0
            )
        else:
            return BrokenLinkSummaryDto(
                total = 5,
                successful = 2,
                redirects = 2,
                broken = 1,
                server_error = 0,
        )
        """

    def testBrokenLinkSummaryDto(self):
        """Test BrokenLinkSummaryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
