# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.broken_link_response_dto import BrokenLinkResponseDto

class TestBrokenLinkResponseDto(unittest.TestCase):
    """BrokenLinkResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrokenLinkResponseDto:
        """Test BrokenLinkResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrokenLinkResponseDto`
        """
        model = BrokenLinkResponseDto()
        if include_optional:
            return BrokenLinkResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'No broken links found.',
                meta = geekflare_api.models.broken_link_meta_dto.BrokenLinkMetaDto(
                    url = 'example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                summary = geekflare_api.models.broken_link_summary_dto.BrokenLinkSummaryDto(
                    total = 5, 
                    successful = 2, 
                    redirects = 2, 
                    broken = 1, 
                    server_error = 0, ),
                data = [{link=https://example.com/, status=200}, {link=https://example.com/articles, status=200}]
            )
        else:
            return BrokenLinkResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'No broken links found.',
                meta = geekflare_api.models.broken_link_meta_dto.BrokenLinkMetaDto(
                    url = 'example.com', 
                    proxy_country = 'United States', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    test = null, ),
                summary = geekflare_api.models.broken_link_summary_dto.BrokenLinkSummaryDto(
                    total = 5, 
                    successful = 2, 
                    redirects = 2, 
                    broken = 1, 
                    server_error = 0, ),
                data = [{link=https://example.com/, status=200}, {link=https://example.com/articles, status=200}],
        )
        """

    def testBrokenLinkResponseDto(self):
        """Test BrokenLinkResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
