# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.meta_scrape_response_dto_data import MetaScrapeResponseDtoData

class TestMetaScrapeResponseDtoData(unittest.TestCase):
    """MetaScrapeResponseDtoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetaScrapeResponseDtoData:
        """Test MetaScrapeResponseDtoData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetaScrapeResponseDtoData`
        """
        model = MetaScrapeResponseDtoData()
        if include_optional:
            return MetaScrapeResponseDtoData(
            )
        else:
            return MetaScrapeResponseDtoData(
        )
        """

    def testMetaScrapeResponseDtoData(self):
        """Test MetaScrapeResponseDtoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
