# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.extraction_schema_dto_fields_inner import ExtractionSchemaDtoFieldsInner

class TestExtractionSchemaDtoFieldsInner(unittest.TestCase):
    """ExtractionSchemaDtoFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtractionSchemaDtoFieldsInner:
        """Test ExtractionSchemaDtoFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractionSchemaDtoFieldsInner`
        """
        model = ExtractionSchemaDtoFieldsInner()
        if include_optional:
            return ExtractionSchemaDtoFieldsInner(
                title = 'Product Name',
                value = Some hardcoded string,
                name = 'title',
                selector = 'h1.product-title',
                type = 'text',
                attribute = 'href',
                fields = [
                    geekflare_api.models.selector_extraction_field_dto.SelectorExtractionFieldDto(
                        name = 'title', 
                        selector = 'h1.product-title', 
                        type = 'text', 
                        attribute = 'href', )
                    ]
            )
        else:
            return ExtractionSchemaDtoFieldsInner(
                title = 'Product Name',
                value = Some hardcoded string,
                name = 'title',
                selector = 'h1.product-title',
                type = 'text',
        )
        """

    def testExtractionSchemaDtoFieldsInner(self):
        """Test ExtractionSchemaDtoFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
