# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search200_response import Search200Response

class TestSearch200Response(unittest.TestCase):
    """Search200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Search200Response:
        """Test Search200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Search200Response`
        """
        model = Search200Response()
        if include_optional:
            return Search200Response(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = <ul><li><a href="...">Title</a></li></ul>
            )
        else:
            return Search200Response(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    time = 'd', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = <ul><li><a href="...">Title</a></li></ul>,
        )
        """

    def testSearch200Response(self):
        """Test Search200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
