# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.site_status_response_dto import SiteStatusResponseDto

class TestSiteStatusResponseDto(unittest.TestCase):
    """SiteStatusResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteStatusResponseDto:
        """Test SiteStatusResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteStatusResponseDto`
        """
        model = SiteStatusResponseDto()
        if include_optional:
            return SiteStatusResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Site is up',
                meta = geekflare_api.models.site_status_meta_dto.SiteStatusMetaDto(
                    url = 'https://example.com', 
                    follow_redirect = True, 
                    redirected_url = https://www.example.com/home, 
                    proxy_country = 'US', 
                    test = null, ),
                data = {statusCode=200, reasonPhrase=OK}
            )
        else:
            return SiteStatusResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                message = 'Site is up',
                meta = geekflare_api.models.site_status_meta_dto.SiteStatusMetaDto(
                    url = 'https://example.com', 
                    follow_redirect = True, 
                    redirected_url = https://www.example.com/home, 
                    proxy_country = 'US', 
                    test = null, ),
                data = {statusCode=200, reasonPhrase=OK},
        )
        """

    def testSiteStatusResponseDto(self):
        """Test SiteStatusResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
