# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.sentiment_ai_prompt_dto import SentimentAiPromptDto

class TestSentimentAiPromptDto(unittest.TestCase):
    """SentimentAiPromptDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SentimentAiPromptDto:
        """Test SentimentAiPromptDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SentimentAiPromptDto`
        """
        model = SentimentAiPromptDto()
        if include_optional:
            return SentimentAiPromptDto(
                type = 'prompt',
                aspects = [sound quality, battery life, comfort, price]
            )
        else:
            return SentimentAiPromptDto(
                type = 'prompt',
        )
        """

    def testSentimentAiPromptDto(self):
        """Test SentimentAiPromptDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
