# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_data_dto_navigation_inner import SearchSerpDataDtoNavigationInner

class TestSearchSerpDataDtoNavigationInner(unittest.TestCase):
    """SearchSerpDataDtoNavigationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpDataDtoNavigationInner:
        """Test SearchSerpDataDtoNavigationInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpDataDtoNavigationInner`
        """
        model = SearchSerpDataDtoNavigationInner()
        if include_optional:
            return SearchSerpDataDtoNavigationInner(
                title = 'Images',
                href = 'https://www.google.com/search?q=ats+for+agencies&udm=2'
            )
        else:
            return SearchSerpDataDtoNavigationInner(
        )
        """

    def testSearchSerpDataDtoNavigationInner(self):
        """Test SearchSerpDataDtoNavigationInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
