# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.ping_response_dto import PingResponseDto

class TestPingResponseDto(unittest.TestCase):
    """PingResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PingResponseDto:
        """Test PingResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingResponseDto`
        """
        model = PingResponseDto()
        if include_optional:
            return PingResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.ping_meta_dto.PingMetaDto(
                    url = 'example.com', 
                    test = null, ),
                data = geekflare_api.models.ping_data_dto.PingDataDto(
                    requests = 4, 
                    loss = 0, 
                    latency = 32.5, 
                    min = 30, 
                    max = 35, 
                    avg = 32.5, 
                    std_dev = 1.5, 
                    ip = '142.250.183.206', )
            )
        else:
            return PingResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.ping_meta_dto.PingMetaDto(
                    url = 'example.com', 
                    test = null, ),
                data = geekflare_api.models.ping_data_dto.PingDataDto(
                    requests = 4, 
                    loss = 0, 
                    latency = 32.5, 
                    min = 30, 
                    max = 35, 
                    avg = 32.5, 
                    std_dev = 1.5, 
                    ip = '142.250.183.206', ),
        )
        """

    def testPingResponseDto(self):
        """Test PingResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
