# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_page_meta_dto import BrandPageMetaDto

class TestBrandPageMetaDto(unittest.TestCase):
    """BrandPageMetaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandPageMetaDto:
        """Test BrandPageMetaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandPageMetaDto`
        """
        model = BrandPageMetaDto()
        if include_optional:
            return BrandPageMetaDto(
                title = '',
                theme_color = '',
                canonical_url = '',
                language = '',
                og_url = '',
                og_type = '',
                og_title = '',
                og_description = '',
                og_image = '',
                og_image_type = '',
                og_image_width = '',
                og_image_height = '',
                og_site_name = '',
                og_locale = '',
                twitter_card = '',
                twitter_site = ''
            )
        else:
            return BrandPageMetaDto(
        )
        """

    def testBrandPageMetaDto(self):
        """Test BrandPageMetaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
