# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.network_dto import NetworkDto

class TestNetworkDto(unittest.TestCase):
    """NetworkDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkDto:
        """Test NetworkDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkDto`
        """
        model = NetworkDto()
        if include_optional:
            return NetworkDto(
                protocol = 'h2',
                remote_ip = '1.1.1.1',
                bytes_read = 15400
            )
        else:
            return NetworkDto(
                protocol = 'h2',
                bytes_read = 15400,
        )
        """

    def testNetworkDto(self):
        """Test NetworkDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
