# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.load_time_multi_location_response_dto_summary import LoadTimeMultiLocationResponseDtoSummary

class TestLoadTimeMultiLocationResponseDtoSummary(unittest.TestCase):
    """LoadTimeMultiLocationResponseDtoSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadTimeMultiLocationResponseDtoSummary:
        """Test LoadTimeMultiLocationResponseDtoSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadTimeMultiLocationResponseDtoSummary`
        """
        model = LoadTimeMultiLocationResponseDtoSummary()
        if include_optional:
            return LoadTimeMultiLocationResponseDtoSummary(
                reachable = [us, gb, ca]
            )
        else:
            return LoadTimeMultiLocationResponseDtoSummary(
        )
        """

    def testLoadTimeMultiLocationResponseDtoSummary(self):
        """Test LoadTimeMultiLocationResponseDtoSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
