# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.web_scrape_dto import WebScrapeDto

class TestWebScrapeDto(unittest.TestCase):
    """WebScrapeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebScrapeDto:
        """Test WebScrapeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebScrapeDto`
        """
        model = WebScrapeDto()
        if include_optional:
            return WebScrapeDto(
                url = 'https://example.com',
                device = 'desktop',
                block_ads = True,
                render_js = True,
                proxy_country = 'us',
                format = html,markdown,
                file_output = False,
                stealth = False,
                wait_time = 2.5,
                extraction_mode = 'default',
                extraction_schema = geekflare_api.models.extraction_schema_dto.ExtractionSchemaDto(
                    name = 'Product Schema', 
                    base_selector = '.product', 
                    fields = [
                        null
                        ], )
            )
        else:
            return WebScrapeDto(
                url = 'https://example.com',
        )
        """

    def testWebScrapeDto(self):
        """Test WebScrapeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
