# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.url2_pdf_response_dto import Url2PdfResponseDto

class TestUrl2PdfResponseDto(unittest.TestCase):
    """Url2PdfResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Url2PdfResponseDto:
        """Test Url2PdfResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Url2PdfResponseDto`
        """
        model = Url2PdfResponseDto()
        if include_optional:
            return Url2PdfResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.url2_pdf_meta_dto.Url2PdfMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    proxy_country = '', 
                    format = 'letter', 
                    orientation = 'landscape', 
                    margin = null, 
                    scale = 1.5, 
                    test = null, ),
                data = 'https://api-assets.example.com/tests/pdf/o5jiqf08bmp93jsll7vb24vs.pdf'
            )
        else:
            return Url2PdfResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.url2_pdf_meta_dto.Url2PdfMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    proxy_country = '', 
                    format = 'letter', 
                    orientation = 'landscape', 
                    margin = null, 
                    scale = 1.5, 
                    test = null, ),
                data = 'https://api-assets.example.com/tests/pdf/o5jiqf08bmp93jsll7vb24vs.pdf',
        )
        """

    def testUrl2PdfResponseDto(self):
        """Test Url2PdfResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
