# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.meta_scrape_dto import MetaScrapeDto

class TestMetaScrapeDto(unittest.TestCase):
    """MetaScrapeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetaScrapeDto:
        """Test MetaScrapeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetaScrapeDto`
        """
        model = MetaScrapeDto()
        if include_optional:
            return MetaScrapeDto(
                url = 'https://example.com',
                device = 'desktop',
                block_ads = True,
                render_js = True,
                proxy_country = 'us',
                format = 'json',
                file_output = False
            )
        else:
            return MetaScrapeDto(
                url = 'https://example.com',
        )
        """

    def testMetaScrapeDto(self):
        """Test MetaScrapeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
