# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_advisory_dto import TlsAdvisoryDto

class TestTlsAdvisoryDto(unittest.TestCase):
    """TlsAdvisoryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsAdvisoryDto:
        """Test TlsAdvisoryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsAdvisoryDto`
        """
        model = TlsAdvisoryDto()
        if include_optional:
            return TlsAdvisoryDto(
                breach = None,
                secure_renegotiation = None,
                ocsp_stapling = None
            )
        else:
            return TlsAdvisoryDto(
                breach = None,
                secure_renegotiation = None,
                ocsp_stapling = None,
        )
        """

    def testTlsAdvisoryDto(self):
        """Test TlsAdvisoryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
