# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.prompt_ai_prompt_dto import PromptAiPromptDto

class TestPromptAiPromptDto(unittest.TestCase):
    """PromptAiPromptDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptAiPromptDto:
        """Test PromptAiPromptDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptAiPromptDto`
        """
        model = PromptAiPromptDto()
        if include_optional:
            return PromptAiPromptDto(
                type = 'prompt',
                query = 'What is the return policy?'
            )
        else:
            return PromptAiPromptDto(
                type = 'prompt',
                query = 'What is the return policy?',
        )
        """

    def testPromptAiPromptDto(self):
        """Test PromptAiPromptDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
