# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.mixed_content_data_dto import MixedContentDataDto

class TestMixedContentDataDto(unittest.TestCase):
    """MixedContentDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MixedContentDataDto:
        """Test MixedContentDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MixedContentDataDto`
        """
        model = MixedContentDataDto()
        if include_optional:
            return MixedContentDataDto(
                insecure = [http://example.com/style.css, http://example.com/script.js],
                secure = [https://example.com/, https://fonts.googleapis.com/css?family=Open+Sans, data:image/svg+xml;base64,PHN2ZyB4bWxucz0i...]
            )
        else:
            return MixedContentDataDto(
                insecure = [http://example.com/style.css, http://example.com/script.js],
                secure = [https://example.com/, https://fonts.googleapis.com/css?family=Open+Sans, data:image/svg+xml;base64,PHN2ZyB4bWxucz0i...],
        )
        """

    def testMixedContentDataDto(self):
        """Test MixedContentDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
