# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.tls_scan_data_dto import TlsScanDataDto

class TestTlsScanDataDto(unittest.TestCase):
    """TlsScanDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TlsScanDataDto:
        """Test TlsScanDataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TlsScanDataDto`
        """
        model = TlsScanDataDto()
        if include_optional:
            return TlsScanDataDto(
                protocols = geekflare_api.models.tls_protocols_dto.TlsProtocolsDto(
                    tls10 = False, 
                    tls11 = False, 
                    tls12 = True, 
                    tls13 = True, ),
                certificate = geekflare_api.models.tls_certificate_dto.TlsCertificateDto(
                    common_name = 'sni.cloudflaressl.com', 
                    subject_alt_name = 'DNS:*.example.com, DNS:sni.cloudflaressl.com, DNS:example.com', 
                    issuer = null, 
                    expiry = 'Jun  6 23:59:59 2023 GMT', )
            )
        else:
            return TlsScanDataDto(
                protocols = geekflare_api.models.tls_protocols_dto.TlsProtocolsDto(
                    tls10 = False, 
                    tls11 = False, 
                    tls12 = True, 
                    tls13 = True, ),
                certificate = geekflare_api.models.tls_certificate_dto.TlsCertificateDto(
                    common_name = 'sni.cloudflaressl.com', 
                    subject_alt_name = 'DNS:*.example.com, DNS:sni.cloudflaressl.com, DNS:example.com', 
                    issuer = null, 
                    expiry = 'Jun  6 23:59:59 2023 GMT', ),
        )
        """

    def testTlsScanDataDto(self):
        """Test TlsScanDataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
