# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.lighthouse_response_dto import LighthouseResponseDto

class TestLighthouseResponseDto(unittest.TestCase):
    """LighthouseResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LighthouseResponseDto:
        """Test LighthouseResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LighthouseResponseDto`
        """
        model = LighthouseResponseDto()
        if include_optional:
            return LighthouseResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.lighthouse_meta_dto.LighthouseMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    proxy_country = '', 
                    test = null, ),
                data = 'https://example.com/report.html'
            )
        else:
            return LighthouseResponseDto(
                timestamp = 1777874383873,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.lighthouse_meta_dto.LighthouseMetaDto(
                    url = 'https://example.com', 
                    device = 'desktop', 
                    follow_redirect = True, 
                    redirected_url = 'https://example.com/', 
                    proxy_country = '', 
                    test = null, ),
                data = 'https://example.com/report.html',
        )
        """

    def testLighthouseResponseDto(self):
        """Test LighthouseResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
