# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.search_serp_response_dto import SearchSerpResponseDto

class TestSearchSerpResponseDto(unittest.TestCase):
    """SearchSerpResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSerpResponseDto:
        """Test SearchSerpResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSerpResponseDto`
        """
        model = SearchSerpResponseDto()
        if include_optional:
            return SearchSerpResponseDto(
                timestamp = 1790698941310,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    limit = 10, 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    city = 'London,England,United Kingdom', 
                    time = 'd', 
                    category = 'general', 
                    include_domains = [reddit.com], 
                    exclude_domains = [pinterest.com], 
                    format = 'json', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = geekflare_api.models.search_serp_data_dto.SearchSerpDataDto(
                    general = geekflare_api.models.search_serp_data_dto_general.SearchSerpDataDto_general(
                        search_engine = 'google', 
                        query = 'ats for agencies', 
                        detected_query = 'ats for agencies', 
                        results_cnt = 128, 
                        search_time = 0.24, 
                        language = 'en', 
                        country_code = 'US', 
                        location = 'United States', 
                        gl = 'US', 
                        mobile = False, 
                        basic_view = False, 
                        search_type = 'text', 
                        page_title = 'ats for agencies - Google Search', 
                        timestamp = '2026-09-29T16:22:20.881Z', ), 
                    input = geekflare_api.models.search_serp_data_dto_input.SearchSerpDataDto_input(
                        original_url = 'https://www.google.com/search?q=ats%20for%20agencies&gl=us', 
                        request_id = 'hl_309dd1bd_fawunsu8b5k', ), 
                    navigation = [
                        geekflare_api.models.search_serp_data_dto_navigation_inner.SearchSerpDataDto_navigation_inner(
                            title = 'Images', 
                            href = 'https://www.google.com/search?q=ats+for+agencies&udm=2', )
                        ], 
                    organic = [
                        geekflare_api.models.search_serp_data_dto_organic_inner.SearchSerpDataDto_organic_inner(
                            link = 'https://recruiterflow.com/', 
                            source = 'Recruiterflow', 
                            display_link = 'https://recruiterflow.com', 
                            title = 'Recruiterflow - Best AI-Native ATS & CRM for Executive ...', 
                            description = 'Recruiterflow is the best AI-Native ATS & CRM software for executive search firms...', 
                            snippet_highlighted_words = [
                                ''
                                ], 
                            extensions = [
                                geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner.SearchSerpDataDto_organic_inner_extensions_inner(
                                    inline = True, 
                                    type = 'text', 
                                    text = 'Jul 15, 2025', 
                                    rank = 1.337, )
                                ], 
                            icon = '', 
                            rank = 1, 
                            global_rank = 1, )
                        ], 
                    news = [
                        None
                        ], 
                    images = [
                        None
                        ], 
                    pagination = geekflare_api.models.search_serp_data_dto_pagination.SearchSerpDataDto_pagination(
                        pages = [
                            geekflare_api.models.search_serp_data_dto_pagination_pages_inner.SearchSerpDataDto_pagination_pages_inner(
                                page = 2, 
                                start = 10, 
                                link = '', )
                            ], 
                        current_page = 1, 
                        next_page = 2, 
                        next_page_start = 10, 
                        next_page_link = '', ), 
                    related = [
                        geekflare_api.models.search_serp_data_dto_related_inner.SearchSerpDataDto_related_inner(
                            text = 'Ats for agencies reddit', 
                            link = '', 
                            rank = 1, 
                            global_rank = 1, )
                        ], 
                    ai_overview = geekflare_api.models.search_serp_data_dto_ai_overview.SearchSerpDataDto_ai_overview(
                        text = '', 
                        html = '', 
                        references = [
                            geekflare_api.models.search_serp_data_dto_ai_overview_references_inner.SearchSerpDataDto_ai_overview_references_inner(
                                title = 'The Best Laptops Under $1,000 We've Tested for 2026 | PCMag', 
                                url = 'https://www.pcmag.com/picks/best-laptops-under-1000', 
                                source = 'PCMag', 
                                snippet = '', )
                            ], ), 
                    people_also_ask = [
                        geekflare_api.models.search_serp_data_dto_people_also_ask_inner.SearchSerpDataDto_people_also_ask_inner(
                            question = 'What is the best ATS for recruiting agencies?', 
                            question_link = '', 
                            question_type = 'ai_overview', 
                            rank = 1, 
                            global_rank = 1, )
                        ], )
            )
        else:
            return SearchSerpResponseDto(
                timestamp = 1790698941310,
                api_status = 'success',
                api_code = 200,
                meta = geekflare_api.models.search_meta_dto.SearchMetaDto(
                    query = 'best running shoes', 
                    limit = 10, 
                    count = 10, 
                    source = web, 
                    location = 'us', 
                    city = 'London,England,United Kingdom', 
                    time = 'd', 
                    category = 'general', 
                    include_domains = [reddit.com], 
                    exclude_domains = [pinterest.com], 
                    format = 'json', 
                    scrape = False, 
                    scrape_limit = 3, 
                    test = null, ),
                data = geekflare_api.models.search_serp_data_dto.SearchSerpDataDto(
                    general = geekflare_api.models.search_serp_data_dto_general.SearchSerpDataDto_general(
                        search_engine = 'google', 
                        query = 'ats for agencies', 
                        detected_query = 'ats for agencies', 
                        results_cnt = 128, 
                        search_time = 0.24, 
                        language = 'en', 
                        country_code = 'US', 
                        location = 'United States', 
                        gl = 'US', 
                        mobile = False, 
                        basic_view = False, 
                        search_type = 'text', 
                        page_title = 'ats for agencies - Google Search', 
                        timestamp = '2026-09-29T16:22:20.881Z', ), 
                    input = geekflare_api.models.search_serp_data_dto_input.SearchSerpDataDto_input(
                        original_url = 'https://www.google.com/search?q=ats%20for%20agencies&gl=us', 
                        request_id = 'hl_309dd1bd_fawunsu8b5k', ), 
                    navigation = [
                        geekflare_api.models.search_serp_data_dto_navigation_inner.SearchSerpDataDto_navigation_inner(
                            title = 'Images', 
                            href = 'https://www.google.com/search?q=ats+for+agencies&udm=2', )
                        ], 
                    organic = [
                        geekflare_api.models.search_serp_data_dto_organic_inner.SearchSerpDataDto_organic_inner(
                            link = 'https://recruiterflow.com/', 
                            source = 'Recruiterflow', 
                            display_link = 'https://recruiterflow.com', 
                            title = 'Recruiterflow - Best AI-Native ATS & CRM for Executive ...', 
                            description = 'Recruiterflow is the best AI-Native ATS & CRM software for executive search firms...', 
                            snippet_highlighted_words = [
                                ''
                                ], 
                            extensions = [
                                geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner.SearchSerpDataDto_organic_inner_extensions_inner(
                                    inline = True, 
                                    type = 'text', 
                                    text = 'Jul 15, 2025', 
                                    rank = 1.337, )
                                ], 
                            icon = '', 
                            rank = 1, 
                            global_rank = 1, )
                        ], 
                    news = [
                        None
                        ], 
                    images = [
                        None
                        ], 
                    pagination = geekflare_api.models.search_serp_data_dto_pagination.SearchSerpDataDto_pagination(
                        pages = [
                            geekflare_api.models.search_serp_data_dto_pagination_pages_inner.SearchSerpDataDto_pagination_pages_inner(
                                page = 2, 
                                start = 10, 
                                link = '', )
                            ], 
                        current_page = 1, 
                        next_page = 2, 
                        next_page_start = 10, 
                        next_page_link = '', ), 
                    related = [
                        geekflare_api.models.search_serp_data_dto_related_inner.SearchSerpDataDto_related_inner(
                            text = 'Ats for agencies reddit', 
                            link = '', 
                            rank = 1, 
                            global_rank = 1, )
                        ], 
                    ai_overview = geekflare_api.models.search_serp_data_dto_ai_overview.SearchSerpDataDto_ai_overview(
                        text = '', 
                        html = '', 
                        references = [
                            geekflare_api.models.search_serp_data_dto_ai_overview_references_inner.SearchSerpDataDto_ai_overview_references_inner(
                                title = 'The Best Laptops Under $1,000 We've Tested for 2026 | PCMag', 
                                url = 'https://www.pcmag.com/picks/best-laptops-under-1000', 
                                source = 'PCMag', 
                                snippet = '', )
                            ], ), 
                    people_also_ask = [
                        geekflare_api.models.search_serp_data_dto_people_also_ask_inner.SearchSerpDataDto_people_also_ask_inner(
                            question = 'What is the best ATS for recruiting agencies?', 
                            question_link = '', 
                            question_type = 'ai_overview', 
                            rank = 1, 
                            global_rank = 1, )
                        ], ),
        )
        """

    def testSearchSerpResponseDto(self):
        """Test SearchSerpResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
