# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_components_dto import BrandComponentsDto

class TestBrandComponentsDto(unittest.TestCase):
    """BrandComponentsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandComponentsDto:
        """Test BrandComponentsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandComponentsDto`
        """
        model = BrandComponentsDto()
        if include_optional:
            return BrandComponentsDto(
                button_primary = geekflare_api.models.brand_button_style_dto.BrandButtonStyleDto(
                    background = '', 
                    text_color = '', 
                    border_color = '', 
                    border_radius = '', 
                    shadow = '', ),
                button_secondary = geekflare_api.models.brand_button_style_dto.BrandButtonStyleDto(
                    background = '', 
                    text_color = '', 
                    border_color = '', 
                    border_radius = '', 
                    shadow = '', ),
                input = geekflare_api.models.brand_button_style_dto.BrandButtonStyleDto(
                    background = '', 
                    text_color = '', 
                    border_color = '', 
                    border_radius = '', 
                    shadow = '', )
            )
        else:
            return BrandComponentsDto(
        )
        """

    def testBrandComponentsDto(self):
        """Test BrandComponentsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
