# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.brand_company_dto import BrandCompanyDto

class TestBrandCompanyDto(unittest.TestCase):
    """BrandCompanyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandCompanyDto:
        """Test BrandCompanyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandCompanyDto`
        """
        model = BrandCompanyDto()
        if include_optional:
            return BrandCompanyDto(
                founded_year = 2012,
                employees_range = '1-10',
                revenue_range = '<$1M',
                kind = 'PRIVATELY_HELD',
                industry = 'Business/Productivity Software',
                location = geekflare_api.models.brand_location_dto.BrandLocationDto(
                    city = geekflare_api.models.city.city(), 
                    state = geekflare_api.models.state.state(), 
                    country = geekflare_api.models.country.country(), 
                    country_code = geekflare_api.models.country_code.countryCode(), ),
                stock_ticker = 'NASDAQ:DBX',
                summary = '',
                target_audience = '',
                target_audience_segments = [
                    'Freelancers'
                    ],
                brand_voice = [
                    ''
                    ],
                use_cases = [
                    ''
                    ]
            )
        else:
            return BrandCompanyDto(
        )
        """

    def testBrandCompanyDto(self):
        """Test BrandCompanyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
