# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geekflare_api.models.extraction_schema_dto import ExtractionSchemaDto

class TestExtractionSchemaDto(unittest.TestCase):
    """ExtractionSchemaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtractionSchemaDto:
        """Test ExtractionSchemaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractionSchemaDto`
        """
        model = ExtractionSchemaDto()
        if include_optional:
            return ExtractionSchemaDto(
                name = 'Product Schema',
                base_selector = '.product',
                fields = [
                    null
                    ]
            )
        else:
            return ExtractionSchemaDto(
                name = 'Product Schema',
                fields = [
                    null
                    ],
        )
        """

    def testExtractionSchemaDto(self):
        """Test ExtractionSchemaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
