# coding: utf-8

# flake8: noqa

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.3.2"

# Define package exports
__all__ = [
    "ApiToolApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BaseErrorResponseDto",
    "BrandButtonStyleDto",
    "BrandColorEntryDto",
    "BrandColorsDto",
    "BrandCompanyDto",
    "BrandComponentsDto",
    "BrandDataDto",
    "BrandDto",
    "BrandFontDto",
    "BrandLinksDto",
    "BrandLocationDto",
    "BrandLogoDto",
    "BrandMetaDto",
    "BrandPageMetaDto",
    "BrandResponseDto",
    "BrandSocialProfileDto",
    "BrandSpacingDto",
    "BrandTypographyDto",
    "BrokenLinkDto",
    "BrokenLinkMetaDto",
    "BrokenLinkResponseDto",
    "BrokenLinkSummaryDto",
    "DefaultExtractionFieldDto",
    "DetectedServiceDto",
    "DnsMetaDto",
    "DnsRecordDto",
    "DnsRecordResponseDto",
    "DnsSecDataDto",
    "DnsSecDto",
    "DnsSecMetaDto",
    "DnsSecResponseDto",
    "ExtractionSchemaDto",
    "ExtractionSchemaDtoFieldsInner",
    "GroundedAnswerDataDto",
    "GroundedAnswerResponseDto",
    "GroundedSourceDto",
    "HealthResponseDto",
    "ImageSearchResponseDto",
    "ImageSearchResultItemDto",
    "KeywordsAiPromptDto",
    "LighthouseDto",
    "LighthouseMetaDto",
    "LighthouseResponseDto",
    "ListingAiPromptDto",
    "LoadTime200Response",
    "LoadTimeDataDto",
    "LoadTimeDto",
    "LoadTimeLocationResultDto",
    "LoadTimeMetaDto",
    "LoadTimeMultiLocationMetaDto",
    "LoadTimeMultiLocationResponseDto",
    "LoadTimeMultiLocationResponseDtoSummary",
    "LoadTimeResponseDto",
    "MarginDto",
    "MetaScrapeDto",
    "MetaScrapeMetaDto",
    "MetaScrapeResponseDto",
    "MetaScrapeResponseDtoData",
    "MixedContentDataDto",
    "MixedContentDto",
    "MixedContentMetaDto",
    "MixedContentResponseDto",
    "MixedContentResponseDtoData",
    "MtrDataDto",
    "MtrDto",
    "MtrMetaDto",
    "MtrResponseDto",
    "NetworkDto",
    "OpenPortDto",
    "OpenPortMetaDto",
    "OpenPortResponseDto",
    "PingDataDto",
    "PingDto",
    "PingMetaDto",
    "PingResponseDto",
    "PortServiceDetectionResultDto",
    "PromptAiPromptDto",
    "ProtocolSupportDto",
    "RedirectCheckDto",
    "RedirectCheckMetaDto",
    "RedirectCheckResponseDto",
    "RedirectHopDto",
    "SchemaAiPromptDto",
    "ScreenshotDto",
    "ScreenshotInlineDto",
    "ScreenshotMetaDto",
    "ScreenshotResponseDto",
    "Search200Response",
    "SearchHtmlResponseDto",
    "SearchMarkdownResponseDto",
    "SearchMetaDto",
    "SearchRequestDto",
    "SearchResponseDto",
    "SearchResultItemDto",
    "SearchSerpDataDto",
    "SearchSerpDataDtoAiOverview",
    "SearchSerpDataDtoAiOverviewReferencesInner",
    "SearchSerpDataDtoGeneral",
    "SearchSerpDataDtoInput",
    "SearchSerpDataDtoNavigationInner",
    "SearchSerpDataDtoOrganicInner",
    "SearchSerpDataDtoOrganicInnerExtensionsInner",
    "SearchSerpDataDtoPagination",
    "SearchSerpDataDtoPaginationPagesInner",
    "SearchSerpDataDtoPeopleAlsoAskInner",
    "SearchSerpDataDtoRelatedInner",
    "SearchSerpResponseDto",
    "SelectorExtractionFieldDto",
    "SentimentAiPromptDto",
    "ServiceHealthResponseDto",
    "ServiceStatus",
    "SiteStatusDto",
    "SiteStatusMetaDto",
    "SiteStatusResponseDto",
    "SummaryAiPromptDto",
    "TestMetaDto",
    "TimingsDto",
    "TlsAdvisoryDto",
    "TlsCertificateChainDto",
    "TlsCertificateChainEntryDto",
    "TlsCertificateDto",
    "TlsCertificateIssuerDto",
    "TlsForwardSecrecyDto",
    "TlsProtocolsDto",
    "TlsScanDataDto",
    "TlsScanDto",
    "TlsScanMetaDto",
    "TlsScanResponseDto",
    "TlsVulnerabilitiesDto",
    "Url2PdfDto",
    "Url2PdfMetaDto",
    "Url2PdfResponseDto",
    "WebScrapeDto",
    "WebScrapeDtoAiPrompt",
    "WebScrapeDtoProxyMode",
    "WebScrapeMetaDto",
    "WebScrapeResponseDto",
    "WebScrapeResponseDtoData",
]

# import apis into sdk package
from geekflare_api.api.api_tool_api import ApiToolApi as ApiToolApi

# import ApiClient
from geekflare_api.api_response import ApiResponse as ApiResponse
from geekflare_api.api_client import ApiClient as ApiClient
from geekflare_api.configuration import Configuration as Configuration
from geekflare_api.exceptions import OpenApiException as OpenApiException
from geekflare_api.exceptions import ApiTypeError as ApiTypeError
from geekflare_api.exceptions import ApiValueError as ApiValueError
from geekflare_api.exceptions import ApiKeyError as ApiKeyError
from geekflare_api.exceptions import ApiAttributeError as ApiAttributeError
from geekflare_api.exceptions import ApiException as ApiException

# import models into sdk package
from geekflare_api.models.base_error_response_dto import BaseErrorResponseDto as BaseErrorResponseDto
from geekflare_api.models.brand_button_style_dto import BrandButtonStyleDto as BrandButtonStyleDto
from geekflare_api.models.brand_color_entry_dto import BrandColorEntryDto as BrandColorEntryDto
from geekflare_api.models.brand_colors_dto import BrandColorsDto as BrandColorsDto
from geekflare_api.models.brand_company_dto import BrandCompanyDto as BrandCompanyDto
from geekflare_api.models.brand_components_dto import BrandComponentsDto as BrandComponentsDto
from geekflare_api.models.brand_data_dto import BrandDataDto as BrandDataDto
from geekflare_api.models.brand_dto import BrandDto as BrandDto
from geekflare_api.models.brand_font_dto import BrandFontDto as BrandFontDto
from geekflare_api.models.brand_links_dto import BrandLinksDto as BrandLinksDto
from geekflare_api.models.brand_location_dto import BrandLocationDto as BrandLocationDto
from geekflare_api.models.brand_logo_dto import BrandLogoDto as BrandLogoDto
from geekflare_api.models.brand_meta_dto import BrandMetaDto as BrandMetaDto
from geekflare_api.models.brand_page_meta_dto import BrandPageMetaDto as BrandPageMetaDto
from geekflare_api.models.brand_response_dto import BrandResponseDto as BrandResponseDto
from geekflare_api.models.brand_social_profile_dto import BrandSocialProfileDto as BrandSocialProfileDto
from geekflare_api.models.brand_spacing_dto import BrandSpacingDto as BrandSpacingDto
from geekflare_api.models.brand_typography_dto import BrandTypographyDto as BrandTypographyDto
from geekflare_api.models.broken_link_dto import BrokenLinkDto as BrokenLinkDto
from geekflare_api.models.broken_link_meta_dto import BrokenLinkMetaDto as BrokenLinkMetaDto
from geekflare_api.models.broken_link_response_dto import BrokenLinkResponseDto as BrokenLinkResponseDto
from geekflare_api.models.broken_link_summary_dto import BrokenLinkSummaryDto as BrokenLinkSummaryDto
from geekflare_api.models.default_extraction_field_dto import DefaultExtractionFieldDto as DefaultExtractionFieldDto
from geekflare_api.models.detected_service_dto import DetectedServiceDto as DetectedServiceDto
from geekflare_api.models.dns_meta_dto import DnsMetaDto as DnsMetaDto
from geekflare_api.models.dns_record_dto import DnsRecordDto as DnsRecordDto
from geekflare_api.models.dns_record_response_dto import DnsRecordResponseDto as DnsRecordResponseDto
from geekflare_api.models.dns_sec_data_dto import DnsSecDataDto as DnsSecDataDto
from geekflare_api.models.dns_sec_dto import DnsSecDto as DnsSecDto
from geekflare_api.models.dns_sec_meta_dto import DnsSecMetaDto as DnsSecMetaDto
from geekflare_api.models.dns_sec_response_dto import DnsSecResponseDto as DnsSecResponseDto
from geekflare_api.models.extraction_schema_dto import ExtractionSchemaDto as ExtractionSchemaDto
from geekflare_api.models.extraction_schema_dto_fields_inner import ExtractionSchemaDtoFieldsInner as ExtractionSchemaDtoFieldsInner
from geekflare_api.models.grounded_answer_data_dto import GroundedAnswerDataDto as GroundedAnswerDataDto
from geekflare_api.models.grounded_answer_response_dto import GroundedAnswerResponseDto as GroundedAnswerResponseDto
from geekflare_api.models.grounded_source_dto import GroundedSourceDto as GroundedSourceDto
from geekflare_api.models.health_response_dto import HealthResponseDto as HealthResponseDto
from geekflare_api.models.image_search_response_dto import ImageSearchResponseDto as ImageSearchResponseDto
from geekflare_api.models.image_search_result_item_dto import ImageSearchResultItemDto as ImageSearchResultItemDto
from geekflare_api.models.keywords_ai_prompt_dto import KeywordsAiPromptDto as KeywordsAiPromptDto
from geekflare_api.models.lighthouse_dto import LighthouseDto as LighthouseDto
from geekflare_api.models.lighthouse_meta_dto import LighthouseMetaDto as LighthouseMetaDto
from geekflare_api.models.lighthouse_response_dto import LighthouseResponseDto as LighthouseResponseDto
from geekflare_api.models.listing_ai_prompt_dto import ListingAiPromptDto as ListingAiPromptDto
from geekflare_api.models.load_time200_response import LoadTime200Response as LoadTime200Response
from geekflare_api.models.load_time_data_dto import LoadTimeDataDto as LoadTimeDataDto
from geekflare_api.models.load_time_dto import LoadTimeDto as LoadTimeDto
from geekflare_api.models.load_time_location_result_dto import LoadTimeLocationResultDto as LoadTimeLocationResultDto
from geekflare_api.models.load_time_meta_dto import LoadTimeMetaDto as LoadTimeMetaDto
from geekflare_api.models.load_time_multi_location_meta_dto import LoadTimeMultiLocationMetaDto as LoadTimeMultiLocationMetaDto
from geekflare_api.models.load_time_multi_location_response_dto import LoadTimeMultiLocationResponseDto as LoadTimeMultiLocationResponseDto
from geekflare_api.models.load_time_multi_location_response_dto_summary import LoadTimeMultiLocationResponseDtoSummary as LoadTimeMultiLocationResponseDtoSummary
from geekflare_api.models.load_time_response_dto import LoadTimeResponseDto as LoadTimeResponseDto
from geekflare_api.models.margin_dto import MarginDto as MarginDto
from geekflare_api.models.meta_scrape_dto import MetaScrapeDto as MetaScrapeDto
from geekflare_api.models.meta_scrape_meta_dto import MetaScrapeMetaDto as MetaScrapeMetaDto
from geekflare_api.models.meta_scrape_response_dto import MetaScrapeResponseDto as MetaScrapeResponseDto
from geekflare_api.models.meta_scrape_response_dto_data import MetaScrapeResponseDtoData as MetaScrapeResponseDtoData
from geekflare_api.models.mixed_content_data_dto import MixedContentDataDto as MixedContentDataDto
from geekflare_api.models.mixed_content_dto import MixedContentDto as MixedContentDto
from geekflare_api.models.mixed_content_meta_dto import MixedContentMetaDto as MixedContentMetaDto
from geekflare_api.models.mixed_content_response_dto import MixedContentResponseDto as MixedContentResponseDto
from geekflare_api.models.mixed_content_response_dto_data import MixedContentResponseDtoData as MixedContentResponseDtoData
from geekflare_api.models.mtr_data_dto import MtrDataDto as MtrDataDto
from geekflare_api.models.mtr_dto import MtrDto as MtrDto
from geekflare_api.models.mtr_meta_dto import MtrMetaDto as MtrMetaDto
from geekflare_api.models.mtr_response_dto import MtrResponseDto as MtrResponseDto
from geekflare_api.models.network_dto import NetworkDto as NetworkDto
from geekflare_api.models.open_port_dto import OpenPortDto as OpenPortDto
from geekflare_api.models.open_port_meta_dto import OpenPortMetaDto as OpenPortMetaDto
from geekflare_api.models.open_port_response_dto import OpenPortResponseDto as OpenPortResponseDto
from geekflare_api.models.ping_data_dto import PingDataDto as PingDataDto
from geekflare_api.models.ping_dto import PingDto as PingDto
from geekflare_api.models.ping_meta_dto import PingMetaDto as PingMetaDto
from geekflare_api.models.ping_response_dto import PingResponseDto as PingResponseDto
from geekflare_api.models.port_service_detection_result_dto import PortServiceDetectionResultDto as PortServiceDetectionResultDto
from geekflare_api.models.prompt_ai_prompt_dto import PromptAiPromptDto as PromptAiPromptDto
from geekflare_api.models.protocol_support_dto import ProtocolSupportDto as ProtocolSupportDto
from geekflare_api.models.redirect_check_dto import RedirectCheckDto as RedirectCheckDto
from geekflare_api.models.redirect_check_meta_dto import RedirectCheckMetaDto as RedirectCheckMetaDto
from geekflare_api.models.redirect_check_response_dto import RedirectCheckResponseDto as RedirectCheckResponseDto
from geekflare_api.models.redirect_hop_dto import RedirectHopDto as RedirectHopDto
from geekflare_api.models.schema_ai_prompt_dto import SchemaAiPromptDto as SchemaAiPromptDto
from geekflare_api.models.screenshot_dto import ScreenshotDto as ScreenshotDto
from geekflare_api.models.screenshot_inline_dto import ScreenshotInlineDto as ScreenshotInlineDto
from geekflare_api.models.screenshot_meta_dto import ScreenshotMetaDto as ScreenshotMetaDto
from geekflare_api.models.screenshot_response_dto import ScreenshotResponseDto as ScreenshotResponseDto
from geekflare_api.models.search200_response import Search200Response as Search200Response
from geekflare_api.models.search_html_response_dto import SearchHtmlResponseDto as SearchHtmlResponseDto
from geekflare_api.models.search_markdown_response_dto import SearchMarkdownResponseDto as SearchMarkdownResponseDto
from geekflare_api.models.search_meta_dto import SearchMetaDto as SearchMetaDto
from geekflare_api.models.search_request_dto import SearchRequestDto as SearchRequestDto
from geekflare_api.models.search_response_dto import SearchResponseDto as SearchResponseDto
from geekflare_api.models.search_result_item_dto import SearchResultItemDto as SearchResultItemDto
from geekflare_api.models.search_serp_data_dto import SearchSerpDataDto as SearchSerpDataDto
from geekflare_api.models.search_serp_data_dto_ai_overview import SearchSerpDataDtoAiOverview as SearchSerpDataDtoAiOverview
from geekflare_api.models.search_serp_data_dto_ai_overview_references_inner import SearchSerpDataDtoAiOverviewReferencesInner as SearchSerpDataDtoAiOverviewReferencesInner
from geekflare_api.models.search_serp_data_dto_general import SearchSerpDataDtoGeneral as SearchSerpDataDtoGeneral
from geekflare_api.models.search_serp_data_dto_input import SearchSerpDataDtoInput as SearchSerpDataDtoInput
from geekflare_api.models.search_serp_data_dto_navigation_inner import SearchSerpDataDtoNavigationInner as SearchSerpDataDtoNavigationInner
from geekflare_api.models.search_serp_data_dto_organic_inner import SearchSerpDataDtoOrganicInner as SearchSerpDataDtoOrganicInner
from geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner import SearchSerpDataDtoOrganicInnerExtensionsInner as SearchSerpDataDtoOrganicInnerExtensionsInner
from geekflare_api.models.search_serp_data_dto_pagination import SearchSerpDataDtoPagination as SearchSerpDataDtoPagination
from geekflare_api.models.search_serp_data_dto_pagination_pages_inner import SearchSerpDataDtoPaginationPagesInner as SearchSerpDataDtoPaginationPagesInner
from geekflare_api.models.search_serp_data_dto_people_also_ask_inner import SearchSerpDataDtoPeopleAlsoAskInner as SearchSerpDataDtoPeopleAlsoAskInner
from geekflare_api.models.search_serp_data_dto_related_inner import SearchSerpDataDtoRelatedInner as SearchSerpDataDtoRelatedInner
from geekflare_api.models.search_serp_response_dto import SearchSerpResponseDto as SearchSerpResponseDto
from geekflare_api.models.selector_extraction_field_dto import SelectorExtractionFieldDto as SelectorExtractionFieldDto
from geekflare_api.models.sentiment_ai_prompt_dto import SentimentAiPromptDto as SentimentAiPromptDto
from geekflare_api.models.service_health_response_dto import ServiceHealthResponseDto as ServiceHealthResponseDto
from geekflare_api.models.service_status import ServiceStatus as ServiceStatus
from geekflare_api.models.site_status_dto import SiteStatusDto as SiteStatusDto
from geekflare_api.models.site_status_meta_dto import SiteStatusMetaDto as SiteStatusMetaDto
from geekflare_api.models.site_status_response_dto import SiteStatusResponseDto as SiteStatusResponseDto
from geekflare_api.models.summary_ai_prompt_dto import SummaryAiPromptDto as SummaryAiPromptDto
from geekflare_api.models.test_meta_dto import TestMetaDto as TestMetaDto
from geekflare_api.models.timings_dto import TimingsDto as TimingsDto
from geekflare_api.models.tls_advisory_dto import TlsAdvisoryDto as TlsAdvisoryDto
from geekflare_api.models.tls_certificate_chain_dto import TlsCertificateChainDto as TlsCertificateChainDto
from geekflare_api.models.tls_certificate_chain_entry_dto import TlsCertificateChainEntryDto as TlsCertificateChainEntryDto
from geekflare_api.models.tls_certificate_dto import TlsCertificateDto as TlsCertificateDto
from geekflare_api.models.tls_certificate_issuer_dto import TlsCertificateIssuerDto as TlsCertificateIssuerDto
from geekflare_api.models.tls_forward_secrecy_dto import TlsForwardSecrecyDto as TlsForwardSecrecyDto
from geekflare_api.models.tls_protocols_dto import TlsProtocolsDto as TlsProtocolsDto
from geekflare_api.models.tls_scan_data_dto import TlsScanDataDto as TlsScanDataDto
from geekflare_api.models.tls_scan_dto import TlsScanDto as TlsScanDto
from geekflare_api.models.tls_scan_meta_dto import TlsScanMetaDto as TlsScanMetaDto
from geekflare_api.models.tls_scan_response_dto import TlsScanResponseDto as TlsScanResponseDto
from geekflare_api.models.tls_vulnerabilities_dto import TlsVulnerabilitiesDto as TlsVulnerabilitiesDto
from geekflare_api.models.url2_pdf_dto import Url2PdfDto as Url2PdfDto
from geekflare_api.models.url2_pdf_meta_dto import Url2PdfMetaDto as Url2PdfMetaDto
from geekflare_api.models.url2_pdf_response_dto import Url2PdfResponseDto as Url2PdfResponseDto
from geekflare_api.models.web_scrape_dto import WebScrapeDto as WebScrapeDto
from geekflare_api.models.web_scrape_dto_ai_prompt import WebScrapeDtoAiPrompt as WebScrapeDtoAiPrompt
from geekflare_api.models.web_scrape_dto_proxy_mode import WebScrapeDtoProxyMode as WebScrapeDtoProxyMode
from geekflare_api.models.web_scrape_meta_dto import WebScrapeMetaDto as WebScrapeMetaDto
from geekflare_api.models.web_scrape_response_dto import WebScrapeResponseDto as WebScrapeResponseDto
from geekflare_api.models.web_scrape_response_dto_data import WebScrapeResponseDtoData as WebScrapeResponseDtoData

