# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrandPageMetaDto(BaseModel):
    """
    Meta tags scraped from the page head. Which tags are present depends on what the site itself publishes — not every site sets every Open Graph or Twitter Card tag.
    """ # noqa: E501
    title: Optional[StrictStr] = None
    theme_color: Optional[StrictStr] = Field(default=None, alias="themeColor")
    canonical_url: Optional[StrictStr] = Field(default=None, alias="canonicalUrl")
    language: Optional[StrictStr] = None
    og_url: Optional[StrictStr] = Field(default=None, alias="og:url")
    og_type: Optional[StrictStr] = Field(default=None, alias="og:type")
    og_title: Optional[StrictStr] = Field(default=None, alias="og:title")
    og_description: Optional[StrictStr] = Field(default=None, alias="og:description")
    og_image: Optional[StrictStr] = Field(default=None, alias="og:image")
    og_image_type: Optional[StrictStr] = Field(default=None, alias="og:image:type")
    og_image_width: Optional[StrictStr] = Field(default=None, alias="og:image:width")
    og_image_height: Optional[StrictStr] = Field(default=None, alias="og:image:height")
    og_site_name: Optional[StrictStr] = Field(default=None, alias="og:site_name")
    og_locale: Optional[StrictStr] = Field(default=None, alias="og:locale")
    twitter_card: Optional[StrictStr] = Field(default=None, alias="twitter:card")
    twitter_site: Optional[StrictStr] = Field(default=None, alias="twitter:site")
    __properties: ClassVar[List[str]] = ["title", "themeColor", "canonicalUrl", "language", "og:url", "og:type", "og:title", "og:description", "og:image", "og:image:type", "og:image:width", "og:image:height", "og:site_name", "og:locale", "twitter:card", "twitter:site"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandPageMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandPageMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "themeColor": obj.get("themeColor"),
            "canonicalUrl": obj.get("canonicalUrl"),
            "language": obj.get("language"),
            "og:url": obj.get("og:url"),
            "og:type": obj.get("og:type"),
            "og:title": obj.get("og:title"),
            "og:description": obj.get("og:description"),
            "og:image": obj.get("og:image"),
            "og:image:type": obj.get("og:image:type"),
            "og:image:width": obj.get("og:image:width"),
            "og:image:height": obj.get("og:image:height"),
            "og:site_name": obj.get("og:site_name"),
            "og:locale": obj.get("og:locale"),
            "twitter:card": obj.get("twitter:card"),
            "twitter:site": obj.get("twitter:site")
        })
        return _obj


