# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from geekflare_api.models.brand_colors_dto import BrandColorsDto
from geekflare_api.models.brand_company_dto import BrandCompanyDto
from geekflare_api.models.brand_components_dto import BrandComponentsDto
from geekflare_api.models.brand_font_dto import BrandFontDto
from geekflare_api.models.brand_links_dto import BrandLinksDto
from geekflare_api.models.brand_logo_dto import BrandLogoDto
from geekflare_api.models.brand_page_meta_dto import BrandPageMetaDto
from geekflare_api.models.brand_social_profile_dto import BrandSocialProfileDto
from geekflare_api.models.brand_spacing_dto import BrandSpacingDto
from geekflare_api.models.brand_typography_dto import BrandTypographyDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrandDataDto(BaseModel):
    """
    BrandDataDto
    """ # noqa: E501
    domain: StrictStr = Field(json_schema_extra={"examples": ["stripe.com"]})
    name: Optional[StrictStr] = None
    tagline: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    slogan: Optional[StrictStr] = None
    is_nsfw: Optional[StrictBool] = Field(default=False, alias="isNsfw")
    favicon: Optional[StrictStr] = None
    banner_url: Optional[StrictStr] = Field(default=None, alias="bannerUrl")
    logos: Optional[List[BrandLogoDto]] = None
    colors: Optional[BrandColorsDto] = None
    color_scheme: Optional[StrictStr] = Field(default=None, alias="colorScheme")
    fonts: Optional[List[BrandFontDto]] = None
    font_sizes: Optional[BrandTypographyDto] = Field(default=None, alias="fontSizes")
    components: Optional[BrandComponentsDto] = None
    spacing: Optional[BrandSpacingDto] = None
    social_profiles: Optional[List[BrandSocialProfileDto]] = Field(default=None, alias="socialProfiles")
    links: Optional[BrandLinksDto] = None
    company: Optional[BrandCompanyDto] = None
    page_meta: Optional[BrandPageMetaDto] = Field(default=None, alias="pageMeta")
    __properties: ClassVar[List[str]] = ["domain", "name", "tagline", "description", "slogan", "isNsfw", "favicon", "bannerUrl", "logos", "colors", "colorScheme", "fonts", "fontSizes", "components", "spacing", "socialProfiles", "links", "company", "pageMeta"]

    @field_validator('color_scheme')
    def color_scheme_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['light', 'dark']):
            raise ValueError("must be one of enum values ('light', 'dark')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandDataDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in logos (list)
        _items = []
        if self.logos:
            for _item_logos in self.logos:
                if _item_logos:
                    _items.append(_item_logos.to_dict())
            _dict['logos'] = _items
        # override the default output from pydantic by calling `to_dict()` of colors
        if self.colors:
            _dict['colors'] = self.colors.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in fonts (list)
        _items = []
        if self.fonts:
            for _item_fonts in self.fonts:
                if _item_fonts:
                    _items.append(_item_fonts.to_dict())
            _dict['fonts'] = _items
        # override the default output from pydantic by calling `to_dict()` of font_sizes
        if self.font_sizes:
            _dict['fontSizes'] = self.font_sizes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of components
        if self.components:
            _dict['components'] = self.components.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spacing
        if self.spacing:
            _dict['spacing'] = self.spacing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in social_profiles (list)
        _items = []
        if self.social_profiles:
            for _item_social_profiles in self.social_profiles:
                if _item_social_profiles:
                    _items.append(_item_social_profiles.to_dict())
            _dict['socialProfiles'] = _items
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # override the default output from pydantic by calling `to_dict()` of page_meta
        if self.page_meta:
            _dict['pageMeta'] = self.page_meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandDataDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain": obj.get("domain"),
            "name": obj.get("name"),
            "tagline": obj.get("tagline"),
            "description": obj.get("description"),
            "slogan": obj.get("slogan"),
            "isNsfw": obj.get("isNsfw") if obj.get("isNsfw") is not None else False,
            "favicon": obj.get("favicon"),
            "bannerUrl": obj.get("bannerUrl"),
            "logos": [BrandLogoDto.from_dict(_item) for _item in obj["logos"]] if obj.get("logos") is not None else None,
            "colors": BrandColorsDto.from_dict(obj["colors"]) if obj.get("colors") is not None else None,
            "colorScheme": obj.get("colorScheme"),
            "fonts": [BrandFontDto.from_dict(_item) for _item in obj["fonts"]] if obj.get("fonts") is not None else None,
            "fontSizes": BrandTypographyDto.from_dict(obj["fontSizes"]) if obj.get("fontSizes") is not None else None,
            "components": BrandComponentsDto.from_dict(obj["components"]) if obj.get("components") is not None else None,
            "spacing": BrandSpacingDto.from_dict(obj["spacing"]) if obj.get("spacing") is not None else None,
            "socialProfiles": [BrandSocialProfileDto.from_dict(_item) for _item in obj["socialProfiles"]] if obj.get("socialProfiles") is not None else None,
            "links": BrandLinksDto.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "company": BrandCompanyDto.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "pageMeta": BrandPageMetaDto.from_dict(obj["pageMeta"]) if obj.get("pageMeta") is not None else None
        })
        return _obj


