# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrandLinksDto(BaseModel):
    """
    BrandLinksDto
    """ # noqa: E501
    blog: Optional[StrictStr] = None
    login: Optional[StrictStr] = None
    signup: Optional[StrictStr] = None
    careers: Optional[StrictStr] = None
    contact: Optional[StrictStr] = None
    privacy: Optional[StrictStr] = None
    terms: Optional[StrictStr] = None
    pricing: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["blog", "login", "signup", "careers", "contact", "privacy", "terms", "pricing"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandLinksDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandLinksDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blog": obj.get("blog"),
            "login": obj.get("login"),
            "signup": obj.get("signup"),
            "careers": obj.get("careers"),
            "contact": obj.get("contact"),
            "privacy": obj.get("privacy"),
            "terms": obj.get("terms"),
            "pricing": obj.get("pricing")
        })
        return _obj


