# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.brand_location_dto import BrandLocationDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrandCompanyDto(BaseModel):
    """
    LLM-synthesized company intelligence. Only present when mode is `enriched`. Coverage depends on public information available for the domain — not every field is populated for every site.
    """ # noqa: E501
    founded_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Year the company was founded", alias="foundedYear", json_schema_extra={"examples": [2012]})
    employees_range: Optional[StrictStr] = Field(default=None, description="Approximate employee headcount range", alias="employeesRange", json_schema_extra={"examples": ["1-10"]})
    revenue_range: Optional[StrictStr] = Field(default=None, description="Approximate annual revenue range", alias="revenueRange", json_schema_extra={"examples": ["<$1M"]})
    kind: Optional[StrictStr] = None
    industry: Optional[StrictStr] = Field(default=None, description="Primary industry or category the company operates in", json_schema_extra={"examples": ["Business/Productivity Software"]})
    location: Optional[BrandLocationDto] = None
    stock_ticker: Optional[StrictStr] = Field(default=None, description="Stock ticker symbol, present when kind is PUBLICLY_TRADED", alias="stockTicker", json_schema_extra={"examples": ["NASDAQ:DBX"]})
    summary: Optional[StrictStr] = None
    target_audience: Optional[StrictStr] = Field(default=None, alias="targetAudience")
    target_audience_segments: Optional[List[StrictStr]] = Field(default=None, alias="targetAudienceSegments")
    brand_voice: Optional[List[StrictStr]] = Field(default=None, alias="brandVoice")
    use_cases: Optional[List[StrictStr]] = Field(default=None, alias="useCases")
    __properties: ClassVar[List[str]] = ["foundedYear", "employeesRange", "revenueRange", "kind", "industry", "location", "stockTicker", "summary", "targetAudience", "targetAudienceSegments", "brandVoice", "useCases"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PRIVATELY_HELD', 'PUBLICLY_TRADED', 'NON_PROFIT', 'GOVERNMENT']):
            raise ValueError("must be one of enum values ('PRIVATELY_HELD', 'PUBLICLY_TRADED', 'NON_PROFIT', 'GOVERNMENT')")
        return value

    @field_validator('target_audience_segments')
    def target_audience_segments_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['Freelancers', 'Startups', 'SMBs', 'Mid-Market', 'Enterprise', 'Consumers (B2C)']):
                raise ValueError("each list item must be one of ('Freelancers', 'Startups', 'SMBs', 'Mid-Market', 'Enterprise', 'Consumers (B2C)')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandCompanyDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandCompanyDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "foundedYear": obj.get("foundedYear"),
            "employeesRange": obj.get("employeesRange"),
            "revenueRange": obj.get("revenueRange"),
            "kind": obj.get("kind"),
            "industry": obj.get("industry"),
            "location": BrandLocationDto.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "stockTicker": obj.get("stockTicker"),
            "summary": obj.get("summary"),
            "targetAudience": obj.get("targetAudience"),
            "targetAudienceSegments": obj.get("targetAudienceSegments"),
            "brandVoice": obj.get("brandVoice"),
            "useCases": obj.get("useCases")
        })
        return _obj


