# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from geekflare_api.models.test_meta_dto import TestMetaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrandMetaDto(BaseModel):
    """
    BrandMetaDto
    """ # noqa: E501
    domain: StrictStr = Field(description="The domain that was queried", json_schema_extra={"examples": ["stripe.com"]})
    mode: StrictStr = Field(description="Mode requested", json_schema_extra={"examples": ["standard"]})
    cached: StrictBool = Field(description="Whether this response was served from cache", json_schema_extra={"examples": [True]})
    last_updated: StrictStr = Field(description="When the underlying data was last fetched/updated", alias="lastUpdated", json_schema_extra={"examples": ["2026-06-15T08:32:00Z"]})
    data_age: StrictStr = Field(description="Human-readable age of the cached data", alias="dataAge", json_schema_extra={"examples": ["5d"]})
    refresh_requested: StrictBool = Field(description="Whether a forced refresh was requested", alias="refreshRequested", json_schema_extra={"examples": [False]})
    test: TestMetaDto = Field(description="Test details object")
    __properties: ClassVar[List[str]] = ["domain", "mode", "cached", "lastUpdated", "dataAge", "refreshRequested", "test"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['standard', 'enriched']):
            raise ValueError("must be one of enum values ('standard', 'enriched')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test
        if self.test:
            _dict['test'] = self.test.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain": obj.get("domain"),
            "mode": obj.get("mode"),
            "cached": obj.get("cached"),
            "lastUpdated": obj.get("lastUpdated"),
            "dataAge": obj.get("dataAge"),
            "refreshRequested": obj.get("refreshRequested"),
            "test": TestMetaDto.from_dict(obj["test"]) if obj.get("test") is not None else None
        })
        return _obj


