# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrokenLinkSummaryDto(BaseModel):
    """
    BrokenLinkSummaryDto
    """ # noqa: E501
    total: Union[StrictFloat, StrictInt] = Field(description="Total number of links checked", json_schema_extra={"examples": [5]})
    successful: Union[StrictFloat, StrictInt] = Field(description="Number of successful links (2xx status codes)", json_schema_extra={"examples": [2]})
    redirects: Union[StrictFloat, StrictInt] = Field(description="Number of redirect links (3xx status codes)", json_schema_extra={"examples": [2]})
    broken: Union[StrictFloat, StrictInt] = Field(description="Number of broken links (4xx status codes and DNS/network failures)", json_schema_extra={"examples": [1]})
    server_error: Union[StrictFloat, StrictInt] = Field(description="Number of server errors (5xx status codes)", alias="serverError", json_schema_extra={"examples": [0]})
    forbidden: Union[StrictFloat, StrictInt] = Field(description="Number of forbidden links (403 status codes)", json_schema_extra={"examples": [0]})
    timed_out: Union[StrictFloat, StrictInt] = Field(description="Number of timed-out links", alias="timedOut", json_schema_extra={"examples": [0]})
    __properties: ClassVar[List[str]] = ["total", "successful", "redirects", "broken", "serverError", "forbidden", "timedOut"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrokenLinkSummaryDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrokenLinkSummaryDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "successful": obj.get("successful"),
            "redirects": obj.get("redirects"),
            "broken": obj.get("broken"),
            "serverError": obj.get("serverError"),
            "forbidden": obj.get("forbidden"),
            "timedOut": obj.get("timedOut")
        })
        return _obj


