# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DetectedServiceDto(BaseModel):
    """
    DetectedServiceDto
    """ # noqa: E501
    name: Optional[Dict[str, Any]] = Field(default=None, description="Service name (e.g. \"ssh\", \"http\")", json_schema_extra={"examples": ["ssh"]})
    product: Optional[Dict[str, Any]] = Field(default=None, description="Product name (e.g. \"OpenSSH\")", json_schema_extra={"examples": ["OpenSSH"]})
    version: Optional[Dict[str, Any]] = Field(default=None, description="Product version string", json_schema_extra={"examples": ["8.9p1"]})
    extra_info: Optional[Dict[str, Any]] = Field(default=None, description="Additional context nmap reports alongside the match", alias="extraInfo", json_schema_extra={"examples": ["Ubuntu Linux; protocol 2.0"]})
    os_type: Optional[Dict[str, Any]] = Field(default=None, description="Inferred OS family, if determinable", alias="osType", json_schema_extra={"examples": ["Linux"]})
    __properties: ClassVar[List[str]] = ["name", "product", "version", "extraInfo", "osType"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DetectedServiceDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DetectedServiceDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "product": obj.get("product"),
            "version": obj.get("version"),
            "extraInfo": obj.get("extraInfo"),
            "osType": obj.get("osType")
        })
        return _obj


