# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KeywordsAiPromptDto(BaseModel):
    """
    KeywordsAiPromptDto
    """ # noqa: E501
    type: StrictStr = Field(description="AI extraction mode", json_schema_extra={"examples": ["prompt"]})
    max_keywords: Optional[Union[StrictFloat, StrictInt]] = Field(default=10, description="Maximum number of keywords to return", alias="maxKeywords", json_schema_extra={"examples": [10]})
    include_entities: Optional[StrictBool] = Field(default=False, description="Also extract named entities (organizations, people, dates, laws, locations)", alias="includeEntities")
    __properties: ClassVar[List[str]] = ["type", "maxKeywords", "includeEntities"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['prompt', 'schema', 'listing', 'summary', 'sentiment', 'keywords']):
            raise ValueError("must be one of enum values ('prompt', 'schema', 'listing', 'summary', 'sentiment', 'keywords')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KeywordsAiPromptDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeywordsAiPromptDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "maxKeywords": obj.get("maxKeywords") if obj.get("maxKeywords") is not None else 10,
            "includeEntities": obj.get("includeEntities") if obj.get("includeEntities") is not None else False
        })
        return _obj


