# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from geekflare_api.models.test_meta_dto import TestMetaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LighthouseMetaDto(BaseModel):
    """
    LighthouseMetaDto
    """ # noqa: E501
    url: StrictStr = Field(description="Target URL", json_schema_extra={"examples": ["https://example.com"]})
    device: StrictStr = Field(description="Device type used")
    follow_redirect: StrictBool = Field(description="Whether redirects were followed", alias="followRedirect")
    redirected_url: StrictStr = Field(description="Final URL after redirection (if any)", alias="redirectedURL", json_schema_extra={"examples": ["https://example.com/"]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country used, if any", alias="proxyCountry")
    test: TestMetaDto = Field(description="Test details object")
    __properties: ClassVar[List[str]] = ["url", "device", "followRedirect", "redirectedURL", "proxyCountry", "test"]

    @field_validator('device')
    def device_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['desktop', 'mobile']):
            raise ValueError("must be one of enum values ('desktop', 'mobile')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LighthouseMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test
        if self.test:
            _dict['test'] = self.test.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LighthouseMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "device": obj.get("device"),
            "followRedirect": obj.get("followRedirect"),
            "redirectedURL": obj.get("redirectedURL"),
            "proxyCountry": obj.get("proxyCountry"),
            "test": TestMetaDto.from_dict(obj["test"]) if obj.get("test") is not None else None
        })
        return _obj


