# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from geekflare_api.models.load_time_location_result_dto import LoadTimeLocationResultDto
from geekflare_api.models.load_time_multi_location_meta_dto import LoadTimeMultiLocationMetaDto
from geekflare_api.models.load_time_multi_location_response_dto_summary import LoadTimeMultiLocationResponseDtoSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LoadTimeMultiLocationResponseDto(BaseModel):
    """
    Returned instead of LoadTimeResponseDto when `targetCountries` is set on the request
    """ # noqa: E501
    timestamp: Union[StrictFloat, StrictInt] = Field(description="Timestamp of the request in milliseconds", json_schema_extra={"examples": [1787223157468]})
    api_status: StrictStr = Field(description="API status message", alias="apiStatus", json_schema_extra={"examples": ["success"]})
    api_code: Union[StrictFloat, StrictInt] = Field(description="API status code", alias="apiCode", json_schema_extra={"examples": [200]})
    message: StrictStr = Field(description="Overall summary of reachability across all tested locations", json_schema_extra={"examples": ["Reachable from all 3 tested locations."]})
    meta: LoadTimeMultiLocationMetaDto = Field(description="Metadata about the multi-location test")
    summary: LoadTimeMultiLocationResponseDtoSummary
    locations: List[LoadTimeLocationResultDto] = Field(description="Per-location test results, including the default US server test")
    __properties: ClassVar[List[str]] = ["timestamp", "apiStatus", "apiCode", "message", "meta", "summary", "locations"]

    @field_validator('api_status')
    def api_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'failure']):
            raise ValueError("must be one of enum values ('success', 'failure')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoadTimeMultiLocationResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in locations (list)
        _items = []
        if self.locations:
            for _item_locations in self.locations:
                if _item_locations:
                    _items.append(_item_locations.to_dict())
            _dict['locations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoadTimeMultiLocationResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp": obj.get("timestamp"),
            "apiStatus": obj.get("apiStatus"),
            "apiCode": obj.get("apiCode"),
            "message": obj.get("message"),
            "meta": LoadTimeMultiLocationMetaDto.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "summary": LoadTimeMultiLocationResponseDtoSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "locations": [LoadTimeLocationResultDto.from_dict(_item) for _item in obj["locations"]] if obj.get("locations") is not None else None
        })
        return _obj


