# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from geekflare_api.models.network_dto import NetworkDto
from geekflare_api.models.protocol_support_dto import ProtocolSupportDto
from geekflare_api.models.timings_dto import TimingsDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LoadTimeDataDto(BaseModel):
    """
    LoadTimeDataDto
    """ # noqa: E501
    dns: Union[StrictFloat, StrictInt] = Field(description="Time spent in DNS lookup (ms)", json_schema_extra={"examples": [10]})
    connect: Union[StrictFloat, StrictInt] = Field(description="Time to establish TCP connection (ms)", json_schema_extra={"examples": [12]})
    tls: Union[StrictFloat, StrictInt] = Field(description="Time to complete TLS handshake (ms)", json_schema_extra={"examples": [9]})
    send: Union[StrictFloat, StrictInt] = Field(description="Time to send request (ms)", json_schema_extra={"examples": [19]})
    wait: Union[StrictFloat, StrictInt] = Field(description="Time waiting for response (ms)", json_schema_extra={"examples": [86]})
    total: Union[StrictFloat, StrictInt] = Field(description="Total load time (ms)", json_schema_extra={"examples": [88]})
    status_code: Union[StrictFloat, StrictInt] = Field(description="HTTP status code of the response", alias="statusCode", json_schema_extra={"examples": [404]})
    reason_phrase: StrictStr = Field(description="HTTP reason phrase", alias="reasonPhrase", json_schema_extra={"examples": ["Not Found"]})
    timings: TimingsDto = Field(description="Detailed timing breakdown")
    network: NetworkDto = Field(description="Network information")
    headers: Dict[str, Any] = Field(description="Response headers as key-value pairs", json_schema_extra={"examples": [{"server": "cloudflare", "content-type": "text/html; charset=utf-8", "cache-control": "no-cache"}]})
    protocol_support: ProtocolSupportDto = Field(description="HTTP protocol support information", alias="protocolSupport")
    __properties: ClassVar[List[str]] = ["dns", "connect", "tls", "send", "wait", "total", "statusCode", "reasonPhrase", "timings", "network", "headers", "protocolSupport"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoadTimeDataDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of timings
        if self.timings:
            _dict['timings'] = self.timings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict['network'] = self.network.to_dict()
        # override the default output from pydantic by calling `to_dict()` of protocol_support
        if self.protocol_support:
            _dict['protocolSupport'] = self.protocol_support.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoadTimeDataDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dns": obj.get("dns"),
            "connect": obj.get("connect"),
            "tls": obj.get("tls"),
            "send": obj.get("send"),
            "wait": obj.get("wait"),
            "total": obj.get("total"),
            "statusCode": obj.get("statusCode"),
            "reasonPhrase": obj.get("reasonPhrase"),
            "timings": TimingsDto.from_dict(obj["timings"]) if obj.get("timings") is not None else None,
            "network": NetworkDto.from_dict(obj["network"]) if obj.get("network") is not None else None,
            "headers": obj.get("headers"),
            "protocolSupport": ProtocolSupportDto.from_dict(obj["protocolSupport"]) if obj.get("protocolSupport") is not None else None
        })
        return _obj


