# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MixedContentDataDto(BaseModel):
    """
    MixedContentDataDto
    """ # noqa: E501
    insecure: List[StrictStr] = Field(description="List of insecure (HTTP) resources found on the page", json_schema_extra={"examples": [["http://example.com/style.css", "http://example.com/script.js"]]})
    secure: List[StrictStr] = Field(description="List of secure (HTTPS) resources found on the page", json_schema_extra={"examples": [["https://example.com/", "https://fonts.googleapis.com/css?family=Open+Sans", "data:image/svg+xml;base64,PHN2ZyB4bWxucz0i..."]]})
    __properties: ClassVar[List[str]] = ["insecure", "secure"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MixedContentDataDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MixedContentDataDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "insecure": obj.get("insecure"),
            "secure": obj.get("secure")
        })
        return _obj


