# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MtrDataDto(BaseModel):
    """
    MtrDataDto
    """ # noqa: E501
    hop: Union[StrictFloat, StrictInt] = Field(description="Hop number in the traceroute path", json_schema_extra={"examples": [1]})
    host: StrictStr = Field(description="Host IP or domain name at this hop", json_schema_extra={"examples": ["240.192.18.19"]})
    asn: StrictStr = Field(description="Autonomous System Number (ASN) for the host", json_schema_extra={"examples": ["AS???"]})
    loss: Union[StrictFloat, StrictInt] = Field(description="Packet loss percentage at this hop", json_schema_extra={"examples": [0]})
    sent: Union[StrictFloat, StrictInt] = Field(description="Number of packets sent to this hop", json_schema_extra={"examples": [2]})
    last: Union[StrictFloat, StrictInt] = Field(description="Last recorded round-trip time (RTT) in milliseconds", json_schema_extra={"examples": [0.28]})
    avg: Union[StrictFloat, StrictInt] = Field(description="Average RTT across packets", json_schema_extra={"examples": [0.29]})
    best: Union[StrictFloat, StrictInt] = Field(description="Best (lowest) RTT observed", json_schema_extra={"examples": [0.28]})
    worst: Union[StrictFloat, StrictInt] = Field(description="Worst (highest) RTT observed", json_schema_extra={"examples": [0.3]})
    std_dev: Union[StrictFloat, StrictInt] = Field(description="Standard deviation of RTT measurements", alias="stdDev", json_schema_extra={"examples": [0.01]})
    __properties: ClassVar[List[str]] = ["hop", "host", "asn", "loss", "sent", "last", "avg", "best", "worst", "stdDev"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MtrDataDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MtrDataDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hop": obj.get("hop"),
            "host": obj.get("host"),
            "asn": obj.get("asn"),
            "loss": obj.get("loss"),
            "sent": obj.get("sent"),
            "last": obj.get("last"),
            "avg": obj.get("avg"),
            "best": obj.get("best"),
            "worst": obj.get("worst"),
            "stdDev": obj.get("stdDev")
        })
        return _obj


