# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.open_port_meta_dto import OpenPortMetaDto
from geekflare_api.models.port_service_detection_result_dto import PortServiceDetectionResultDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OpenPortResponseDto(BaseModel):
    """
    OpenPortResponseDto
    """ # noqa: E501
    timestamp: Union[StrictFloat, StrictInt] = Field(description="Timestamp of the request in milliseconds", json_schema_extra={"examples": [1788851167291]})
    api_status: StrictStr = Field(description="API status message", alias="apiStatus", json_schema_extra={"examples": ["success"]})
    api_code: Union[StrictFloat, StrictInt] = Field(description="API status code", alias="apiCode", json_schema_extra={"examples": [200]})
    meta: OpenPortMetaDto = Field(description="Metadata about the request")
    data: List[Union[StrictFloat, StrictInt]] = Field(description="List of open ports found")
    services: Optional[List[PortServiceDetectionResultDto]] = Field(default=None, description="Service/version detection results, present only when detectServices was requested and succeeded")
    services_error: Optional[StrictStr] = Field(default=None, description="Present only when detectServices was requested but could not complete (e.g. nmap error/timeout) — the port list in `data` is still accurate regardless", alias="servicesError", json_schema_extra={"examples": ["Service detection could not complete for this target; the port list above is still accurate."]})
    __properties: ClassVar[List[str]] = ["timestamp", "apiStatus", "apiCode", "meta", "data", "services", "servicesError"]

    @field_validator('api_status')
    def api_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'failure']):
            raise ValueError("must be one of enum values ('success', 'failure')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenPortResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in services (list)
        _items = []
        if self.services:
            for _item_services in self.services:
                if _item_services:
                    _items.append(_item_services.to_dict())
            _dict['services'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenPortResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp": obj.get("timestamp"),
            "apiStatus": obj.get("apiStatus"),
            "apiCode": obj.get("apiCode"),
            "meta": OpenPortMetaDto.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "data": obj.get("data"),
            "services": [PortServiceDetectionResultDto.from_dict(_item) for _item in obj["services"]] if obj.get("services") is not None else None,
            "servicesError": obj.get("servicesError")
        })
        return _obj


