# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OpenPortDto(BaseModel):
    """
    OpenPortDto
    """ # noqa: E501
    url: StrictStr = Field(description="The URL to be checked", json_schema_extra={"examples": ["https://example.com"]})
    top_ports: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Scan only the top N ports (optional)", alias="topPorts", json_schema_extra={"examples": [100]})
    port_ranges: Optional[StrictStr] = Field(default=None, description="Custom port ranges to scan, e.g., \"80,443,1000-1010\"", alias="portRanges", json_schema_extra={"examples": ["80,443,1000-1010"]})
    __properties: ClassVar[List[str]] = ["url", "topPorts", "portRanges"]

    @field_validator('top_ports')
    def top_ports_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([50, 100, 500, 1000, 5000]):
            raise ValueError("must be one of enum values (50, 100, 500, 1000, 5000)")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenPortDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenPortDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "topPorts": obj.get("topPorts"),
            "portRanges": obj.get("portRanges")
        })
        return _obj


