# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProtocolSupportDto(BaseModel):
    """
    ProtocolSupportDto
    """ # noqa: E501
    http10: StrictBool = Field(description="Whether HTTP/1.0 is supported", json_schema_extra={"examples": [False]})
    http11: StrictBool = Field(description="Whether HTTP/1.1 is supported", json_schema_extra={"examples": [True]})
    http2: StrictBool = Field(description="Whether HTTP/2 is supported", json_schema_extra={"examples": [True]})
    http3: StrictBool = Field(description="Whether HTTP/3 is supported", json_schema_extra={"examples": [False]})
    http3_supported_version: Optional[List[StrictStr]] = Field(default=None, description="HTTP/3 supported versions if available", alias="http3SupportedVersion", json_schema_extra={"examples": [["h3-29", "h3"]]})
    __properties: ClassVar[List[str]] = ["http10", "http11", "http2", "http3", "http3SupportedVersion"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProtocolSupportDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProtocolSupportDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "http10": obj.get("http10"),
            "http11": obj.get("http11"),
            "http2": obj.get("http2"),
            "http3": obj.get("http3"),
            "http3SupportedVersion": obj.get("http3SupportedVersion")
        })
        return _obj


