# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScreenshotDto(BaseModel):
    """
    ScreenshotDto
    """ # noqa: E501
    url: StrictStr = Field(description="Target URL", json_schema_extra={"examples": ["https://example.com"]})
    device: Optional[StrictStr] = Field(default='desktop', description="Device type to emulate. Defaults to desktop.", json_schema_extra={"examples": ["desktop"]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country code to route the request", alias="proxyCountry", json_schema_extra={"examples": ["us"]})
    type: Optional[StrictStr] = Field(default='png', description="File type of screenshot. Defaults to png.", json_schema_extra={"examples": ["png"]})
    full_page: Optional[StrictBool] = Field(default=False, description="Take full-page screenshot", alias="fullPage", json_schema_extra={"examples": [True]})
    block_ads: Optional[StrictBool] = Field(default=True, description="Block ads on the page", alias="blockAds", json_schema_extra={"examples": [True]})
    hide_cookie: Optional[StrictBool] = Field(default=True, description="Hide cookie popups", alias="hideCookie", json_schema_extra={"examples": [True]})
    skip_captcha: Optional[StrictBool] = Field(default=True, description="Try to bypass captcha", alias="skipCaptcha", json_schema_extra={"examples": [True]})
    add_timestamp: Optional[StrictBool] = Field(default=False, description="Add timestamp watermark", alias="addTimestamp", json_schema_extra={"examples": [True]})
    page_height: Optional[Union[Annotated[float, Field(le=5000, strict=True, ge=100)], Annotated[int, Field(le=5000, strict=True, ge=100)]]] = Field(default=None, description="Height of the page (for partial screenshot)", alias="pageHeight", json_schema_extra={"examples": [2000]})
    viewport_width: Optional[Union[Annotated[float, Field(le=3840, strict=True, ge=320)], Annotated[int, Field(le=3840, strict=True, ge=320)]]] = Field(default=None, description="Width of the viewport", alias="viewportWidth", json_schema_extra={"examples": [1280]})
    viewport_height: Optional[Union[Annotated[float, Field(le=2160, strict=True, ge=240)], Annotated[int, Field(le=2160, strict=True, ge=240)]]] = Field(default=None, description="Height of the viewport", alias="viewportHeight", json_schema_extra={"examples": [800]})
    theme: Optional[StrictStr] = Field(default='auto', description="Theme to use for rendering", json_schema_extra={"examples": ["auto"]})
    remove_background: Optional[StrictBool] = Field(default=None, description="Remove background from screenshot", alias="removeBackground", json_schema_extra={"examples": [False]})
    highlight_links: Optional[StrictBool] = Field(default=None, description="Highlight links on the page", alias="highlightLinks", json_schema_extra={"examples": [False]})
    delay: Optional[Union[Annotated[float, Field(le=10, strict=True, ge=0)], Annotated[int, Field(le=10, strict=True, ge=0)]]] = Field(default=None, description="Delay before taking screenshot (in seconds)", json_schema_extra={"examples": [2]})
    disable_animations: Optional[StrictBool] = Field(default=None, description="Disable animations on the page", alias="disableAnimations", json_schema_extra={"examples": [False]})
    quality: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=10)], Annotated[int, Field(le=100, strict=True, ge=10)]]] = Field(default=None, description="Image quality (for JPEG/WEBP)", json_schema_extra={"examples": [90]})
    scale_factor: Optional[Union[Annotated[float, Field(le=5, strict=True, ge=0.1)], Annotated[int, Field(le=5, strict=True, ge=1)]]] = Field(default=None, description="Device scale factor", alias="scaleFactor", json_schema_extra={"examples": [1]})
    capture_beyond_viewport: Optional[StrictBool] = Field(default=None, description="Capture beyond viewport if possible", alias="captureBeyondViewport", json_schema_extra={"examples": [True]})
    selector: Optional[StrictStr] = Field(default=None, description="CSS selector to capture only a specific element on the page. Supports class (.), ID (#), and attribute selectors.", json_schema_extra={"examples": [".hero-section"]})
    fallback_to_full_page: Optional[StrictBool] = Field(default=False, description="If true and the selector is not found, falls back to a full-page screenshot instead of returning an error. Default: false.", alias="fallbackToFullPage", json_schema_extra={"examples": [False]})
    inline: Optional[StrictBool] = Field(default=False, description="If true, includes a Base64-encoded image and data URI in the response. Useful for AI agents and LLMs that cannot fetch URLs. Default: false.", json_schema_extra={"examples": [False]})
    __properties: ClassVar[List[str]] = ["url", "device", "proxyCountry", "type", "fullPage", "blockAds", "hideCookie", "skipCaptcha", "addTimestamp", "pageHeight", "viewportWidth", "viewportHeight", "theme", "removeBackground", "highlightLinks", "delay", "disableAnimations", "quality", "scaleFactor", "captureBeyondViewport", "selector", "fallbackToFullPage", "inline"]

    @field_validator('device')
    def device_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['desktop', 'mobile']):
            raise ValueError("must be one of enum values ('desktop', 'mobile')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['png', 'jpeg', 'webp']):
            raise ValueError("must be one of enum values ('png', 'jpeg', 'webp')")
        return value

    @field_validator('theme')
    def theme_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['light', 'dark', 'auto']):
            raise ValueError("must be one of enum values ('light', 'dark', 'auto')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScreenshotDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScreenshotDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "device": obj.get("device") if obj.get("device") is not None else 'desktop',
            "proxyCountry": obj.get("proxyCountry"),
            "type": obj.get("type") if obj.get("type") is not None else 'png',
            "fullPage": obj.get("fullPage") if obj.get("fullPage") is not None else False,
            "blockAds": obj.get("blockAds") if obj.get("blockAds") is not None else True,
            "hideCookie": obj.get("hideCookie") if obj.get("hideCookie") is not None else True,
            "skipCaptcha": obj.get("skipCaptcha") if obj.get("skipCaptcha") is not None else True,
            "addTimestamp": obj.get("addTimestamp") if obj.get("addTimestamp") is not None else False,
            "pageHeight": obj.get("pageHeight"),
            "viewportWidth": obj.get("viewportWidth"),
            "viewportHeight": obj.get("viewportHeight"),
            "theme": obj.get("theme") if obj.get("theme") is not None else 'auto',
            "removeBackground": obj.get("removeBackground"),
            "highlightLinks": obj.get("highlightLinks"),
            "delay": obj.get("delay"),
            "disableAnimations": obj.get("disableAnimations"),
            "quality": obj.get("quality"),
            "scaleFactor": obj.get("scaleFactor"),
            "captureBeyondViewport": obj.get("captureBeyondViewport"),
            "selector": obj.get("selector"),
            "fallbackToFullPage": obj.get("fallbackToFullPage") if obj.get("fallbackToFullPage") is not None else False,
            "inline": obj.get("inline") if obj.get("inline") is not None else False
        })
        return _obj


