# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.test_meta_dto import TestMetaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScreenshotMetaDto(BaseModel):
    """
    ScreenshotMetaDto
    """ # noqa: E501
    url: StrictStr = Field(description="The target URL that was captured", json_schema_extra={"examples": ["https://example.com"]})
    type: StrictStr = Field(description="File type of screenshot", json_schema_extra={"examples": ["png"]})
    device: StrictStr = Field(description="Device type used", json_schema_extra={"examples": ["desktop"]})
    full_page: StrictBool = Field(description="Whether full-page screenshot was taken", alias="fullPage", json_schema_extra={"examples": [False]})
    block_ads: StrictBool = Field(description="Whether ads were blocked", alias="blockAds", json_schema_extra={"examples": [False]})
    hide_cookie: StrictBool = Field(description="Whether cookie popups were hidden", alias="hideCookie", json_schema_extra={"examples": [False]})
    skip_captcha: StrictBool = Field(description="Whether captcha was bypassed", alias="skipCaptcha", json_schema_extra={"examples": [False]})
    add_timestamp: StrictBool = Field(description="Whether timestamp watermark was added", alias="addTimestamp", json_schema_extra={"examples": [False]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country used, if any", alias="proxyCountry")
    page_height: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Height of the page", alias="pageHeight", json_schema_extra={"examples": [2000]})
    viewport_width: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Width of the viewport", alias="viewportWidth", json_schema_extra={"examples": [1280]})
    viewport_height: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Height of the viewport", alias="viewportHeight", json_schema_extra={"examples": [800]})
    theme: Optional[StrictStr] = Field(default=None, description="Theme used", json_schema_extra={"examples": ["auto"]})
    remove_background: Optional[StrictBool] = Field(default=None, description="Whether background was removed", alias="removeBackground", json_schema_extra={"examples": [False]})
    highlight_links: Optional[StrictBool] = Field(default=None, description="Whether links were highlighted", alias="highlightLinks", json_schema_extra={"examples": [False]})
    delay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Delay before screenshot", json_schema_extra={"examples": [2]})
    disable_animations: Optional[StrictBool] = Field(default=None, description="Whether animations were disabled", alias="disableAnimations", json_schema_extra={"examples": [False]})
    quality: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Image quality (JPEG/WEBP)", json_schema_extra={"examples": [90]})
    scale_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Device scale factor", alias="scaleFactor", json_schema_extra={"examples": [1]})
    capture_beyond_viewport: Optional[StrictBool] = Field(default=None, description="Capture beyond viewport", alias="captureBeyondViewport", json_schema_extra={"examples": [True]})
    selector: Optional[StrictStr] = Field(default=None, description="CSS selector that was targeted, if provided", json_schema_extra={"examples": [".hero-section"]})
    fallback_to_full_page: Optional[StrictBool] = Field(default=None, description="Whether fallback to full-page was enabled", alias="fallbackToFullPage", json_schema_extra={"examples": [False]})
    inline: Optional[StrictBool] = Field(default=None, description="Whether inline base64 output was requested", json_schema_extra={"examples": [False]})
    test: TestMetaDto = Field(description="Test details")
    __properties: ClassVar[List[str]] = ["url", "type", "device", "fullPage", "blockAds", "hideCookie", "skipCaptcha", "addTimestamp", "proxyCountry", "pageHeight", "viewportWidth", "viewportHeight", "theme", "removeBackground", "highlightLinks", "delay", "disableAnimations", "quality", "scaleFactor", "captureBeyondViewport", "selector", "fallbackToFullPage", "inline", "test"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScreenshotMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test
        if self.test:
            _dict['test'] = self.test.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScreenshotMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "type": obj.get("type"),
            "device": obj.get("device"),
            "fullPage": obj.get("fullPage"),
            "blockAds": obj.get("blockAds"),
            "hideCookie": obj.get("hideCookie"),
            "skipCaptcha": obj.get("skipCaptcha"),
            "addTimestamp": obj.get("addTimestamp"),
            "proxyCountry": obj.get("proxyCountry"),
            "pageHeight": obj.get("pageHeight"),
            "viewportWidth": obj.get("viewportWidth"),
            "viewportHeight": obj.get("viewportHeight"),
            "theme": obj.get("theme"),
            "removeBackground": obj.get("removeBackground"),
            "highlightLinks": obj.get("highlightLinks"),
            "delay": obj.get("delay"),
            "disableAnimations": obj.get("disableAnimations"),
            "quality": obj.get("quality"),
            "scaleFactor": obj.get("scaleFactor"),
            "captureBeyondViewport": obj.get("captureBeyondViewport"),
            "selector": obj.get("selector"),
            "fallbackToFullPage": obj.get("fallbackToFullPage"),
            "inline": obj.get("inline"),
            "test": TestMetaDto.from_dict(obj["test"]) if obj.get("test") is not None else None
        })
        return _obj


