# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchSerpDataDtoGeneral(BaseModel):
    """
    Details about the search that was run
    """ # noqa: E501
    search_engine: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["google"]})
    query: Optional[StrictStr] = Field(default=None, description="Query as searched", json_schema_extra={"examples": ["ats for agencies"]})
    detected_query: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ats for agencies"]})
    results_cnt: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate total results reported by Google", json_schema_extra={"examples": [128]})
    search_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Search time in seconds", json_schema_extra={"examples": [0.24]})
    language: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["en"]})
    country_code: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["US"]})
    location: Optional[StrictStr] = Field(default=None, description="Location the search was targeted to", json_schema_extra={"examples": ["United States"]})
    gl: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["US"]})
    mobile: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    basic_view: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    search_type: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["text"]})
    page_title: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ats for agencies - Google Search"]})
    timestamp: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2026-09-29T16:22:20.881Z"]})
    __properties: ClassVar[List[str]] = ["search_engine", "query", "detected_query", "results_cnt", "search_time", "language", "country_code", "location", "gl", "mobile", "basic_view", "search_type", "page_title", "timestamp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoGeneral from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoGeneral from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "search_engine": obj.get("search_engine"),
            "query": obj.get("query"),
            "detected_query": obj.get("detected_query"),
            "results_cnt": obj.get("results_cnt"),
            "search_time": obj.get("search_time"),
            "language": obj.get("language"),
            "country_code": obj.get("country_code"),
            "location": obj.get("location"),
            "gl": obj.get("gl"),
            "mobile": obj.get("mobile"),
            "basic_view": obj.get("basic_view"),
            "search_type": obj.get("search_type"),
            "page_title": obj.get("page_title"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


