# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.search_serp_data_dto_organic_inner_extensions_inner import SearchSerpDataDtoOrganicInnerExtensionsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchSerpDataDtoOrganicInner(BaseModel):
    """
    SearchSerpDataDtoOrganicInner
    """ # noqa: E501
    link: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["https://recruiterflow.com/"]})
    source: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Recruiterflow"]})
    display_link: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["https://recruiterflow.com"]})
    title: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Recruiterflow - Best AI-Native ATS & CRM for Executive ..."]})
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Recruiterflow is the best AI-Native ATS & CRM software for executive search firms..."]})
    snippet_highlighted_words: Optional[List[StrictStr]] = Field(default=None, description="Portions of the snippet Google highlights")
    extensions: Optional[List[SearchSerpDataDtoOrganicInnerExtensionsInner]] = Field(default=None, description="Extra info shown with the result, such as a date")
    icon: Optional[StrictStr] = Field(default=None, description="Site icon as a data URI")
    rank: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Position within this section", json_schema_extra={"examples": [1]})
    global_rank: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Position across the whole results page", json_schema_extra={"examples": [1]})
    __properties: ClassVar[List[str]] = ["link", "source", "display_link", "title", "description", "snippet_highlighted_words", "extensions", "icon", "rank", "global_rank"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoOrganicInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in extensions (list)
        _items = []
        if self.extensions:
            for _item_extensions in self.extensions:
                if _item_extensions:
                    _items.append(_item_extensions.to_dict())
            _dict['extensions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoOrganicInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "link": obj.get("link"),
            "source": obj.get("source"),
            "display_link": obj.get("display_link"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "snippet_highlighted_words": obj.get("snippet_highlighted_words"),
            "extensions": [SearchSerpDataDtoOrganicInnerExtensionsInner.from_dict(_item) for _item in obj["extensions"]] if obj.get("extensions") is not None else None,
            "icon": obj.get("icon"),
            "rank": obj.get("rank"),
            "global_rank": obj.get("global_rank")
        })
        return _obj


