# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.search_serp_data_dto_pagination_pages_inner import SearchSerpDataDtoPaginationPagesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchSerpDataDtoPagination(BaseModel):
    """
    SearchSerpDataDtoPagination
    """ # noqa: E501
    pages: Optional[List[SearchSerpDataDtoPaginationPagesInner]] = None
    current_page: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [1]})
    next_page: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [2]})
    next_page_start: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, json_schema_extra={"examples": [10]})
    next_page_link: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["pages", "current_page", "next_page", "next_page_start", "next_page_link"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoPagination from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pages (list)
        _items = []
        if self.pages:
            for _item_pages in self.pages:
                if _item_pages:
                    _items.append(_item_pages.to_dict())
            _dict['pages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoPagination from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pages": [SearchSerpDataDtoPaginationPagesInner.from_dict(_item) for _item in obj["pages"]] if obj.get("pages") is not None else None,
            "current_page": obj.get("current_page"),
            "next_page": obj.get("next_page"),
            "next_page_start": obj.get("next_page_start"),
            "next_page_link": obj.get("next_page_link")
        })
        return _obj


