# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from geekflare_api.models.image_search_response_dto import ImageSearchResponseDto
from geekflare_api.models.search_html_response_dto import SearchHtmlResponseDto
from geekflare_api.models.search_markdown_response_dto import SearchMarkdownResponseDto
from geekflare_api.models.search_response_dto import SearchResponseDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SEARCH200RESPONSE_ONE_OF_SCHEMAS = ["ImageSearchResponseDto", "SearchHtmlResponseDto", "SearchMarkdownResponseDto", "SearchResponseDto"]

class Search200Response(BaseModel):
    """
    Search200Response
    """
    # data type: SearchResponseDto
    oneof_schema_1_validator: Optional[SearchResponseDto] = None
    # data type: ImageSearchResponseDto
    oneof_schema_2_validator: Optional[ImageSearchResponseDto] = None
    # data type: SearchMarkdownResponseDto
    oneof_schema_3_validator: Optional[SearchMarkdownResponseDto] = None
    # data type: SearchHtmlResponseDto
    oneof_schema_4_validator: Optional[SearchHtmlResponseDto] = None
    actual_instance: Optional[Union[ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto]] = None
    one_of_schemas: Set[str] = { "ImageSearchResponseDto", "SearchHtmlResponseDto", "SearchMarkdownResponseDto", "SearchResponseDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Search200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: SearchResponseDto
        if not isinstance(v, SearchResponseDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SearchResponseDto`")
        else:
            match += 1
        # validate data type: ImageSearchResponseDto
        if not isinstance(v, ImageSearchResponseDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageSearchResponseDto`")
        else:
            match += 1
        # validate data type: SearchMarkdownResponseDto
        if not isinstance(v, SearchMarkdownResponseDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SearchMarkdownResponseDto`")
        else:
            match += 1
        # validate data type: SearchHtmlResponseDto
        if not isinstance(v, SearchHtmlResponseDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SearchHtmlResponseDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Search200Response with oneOf schemas: ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Search200Response with oneOf schemas: ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SearchResponseDto
        try:
            instance.actual_instance = SearchResponseDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ImageSearchResponseDto
        try:
            instance.actual_instance = ImageSearchResponseDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SearchMarkdownResponseDto
        try:
            instance.actual_instance = SearchMarkdownResponseDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SearchHtmlResponseDto
        try:
            instance.actual_instance = SearchHtmlResponseDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Search200Response with oneOf schemas: ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Search200Response with oneOf schemas: ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ImageSearchResponseDto, SearchHtmlResponseDto, SearchMarkdownResponseDto, SearchResponseDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


