# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.test_meta_dto import TestMetaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchMetaDto(BaseModel):
    """
    SearchMetaDto
    """ # noqa: E501
    query: StrictStr = Field(description="Original query", json_schema_extra={"examples": ["best running shoes"]})
    limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of results requested", json_schema_extra={"examples": [10]})
    count: Union[StrictFloat, StrictInt] = Field(description="Number of results returned", json_schema_extra={"examples": [10]})
    source: List[StrictStr] = Field(description="Search source used", json_schema_extra={"examples": ["web"]})
    location: StrictStr = Field(description="Country used for ranking", json_schema_extra={"examples": ["us"]})
    city: Optional[StrictStr] = Field(default=None, description="City used for localized results, if one was requested", json_schema_extra={"examples": ["London,England,United Kingdom"]})
    time: StrictStr = Field(description="Time filter applied", json_schema_extra={"examples": ["d"]})
    category: Optional[StrictStr] = Field(default=None, description="Category filter applied", json_schema_extra={"examples": ["general"]})
    include_domains: Optional[List[StrictStr]] = Field(default=None, description="Domains results were restricted to, if any", alias="includeDomains", json_schema_extra={"examples": [["reddit.com"]]})
    exclude_domains: Optional[List[StrictStr]] = Field(default=None, description="Domains excluded from results, if any", alias="excludeDomains", json_schema_extra={"examples": [["pinterest.com"]]})
    format: Optional[StrictStr] = Field(default=None, description="Output format requested", json_schema_extra={"examples": ["json"]})
    scrape: StrictBool = Field(description="Whether URL scraping was enabled", json_schema_extra={"examples": [False]})
    scrape_limit: Union[StrictFloat, StrictInt] = Field(description="Number of URLs scraped", alias="scrapeLimit", json_schema_extra={"examples": [3]})
    test: TestMetaDto = Field(description="Test metadata")
    __properties: ClassVar[List[str]] = ["query", "limit", "count", "source", "location", "city", "time", "category", "includeDomains", "excludeDomains", "format", "scrape", "scrapeLimit", "test"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test
        if self.test:
            _dict['test'] = self.test.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "limit": obj.get("limit"),
            "count": obj.get("count"),
            "source": obj.get("source"),
            "location": obj.get("location"),
            "city": obj.get("city"),
            "time": obj.get("time"),
            "category": obj.get("category"),
            "includeDomains": obj.get("includeDomains"),
            "excludeDomains": obj.get("excludeDomains"),
            "format": obj.get("format"),
            "scrape": obj.get("scrape"),
            "scrapeLimit": obj.get("scrapeLimit"),
            "test": TestMetaDto.from_dict(obj["test"]) if obj.get("test") is not None else None
        })
        return _obj


