# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchRequestDto(BaseModel):
    """
    SearchRequestDto
    """ # noqa: E501
    query: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="Search query", json_schema_extra={"examples": ["best running shoes"]})
    limit: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=1)], Annotated[int, Field(le=100, strict=True, ge=1)]]] = Field(default=10, description="Number of results", json_schema_extra={"examples": [10]})
    time: Optional[StrictStr] = Field(default='any', description="Time filter (h, d, w, m, y or h2, d7, etc.)", json_schema_extra={"examples": ["d"]})
    location: Optional[StrictStr] = Field(default='us', description="Country code (ISO alpha-2)", json_schema_extra={"examples": ["us"]})
    source: Optional[StrictStr] = Field(default='web', description="Search source", json_schema_extra={"examples": ["web"]})
    category: Optional[StrictStr] = Field(default='general', description="Category filter", json_schema_extra={"examples": ["code"]})
    include_domains: Optional[List[StrictStr]] = Field(default=None, description="Include only these domains", alias="includeDomains", json_schema_extra={"examples": [["reddit.com", "stackoverflow.com"]]})
    exclude_domains: Optional[List[StrictStr]] = Field(default=None, description="Exclude these domains", alias="excludeDomains", json_schema_extra={"examples": [["pinterest.com"]]})
    format: Optional[StrictStr] = Field(default='json', description="Output format")
    scrape: Optional[StrictBool] = Field(default=False, description="scrape and extract content from SERP result URLs", json_schema_extra={"examples": [False]})
    scrape_limit: Optional[Union[Annotated[float, Field(le=10, strict=True, ge=1)], Annotated[int, Field(le=10, strict=True, ge=1)]]] = Field(default=3, description="Number of URLs to scrape (requires scrape: true)", alias="scrapeLimit", json_schema_extra={"examples": [3]})
    grounded_answer: Optional[StrictBool] = Field(default=False, description="Use AI to synthesize a grounded answer from search results.", alias="groundedAnswer", json_schema_extra={"examples": [False]})
    __properties: ClassVar[List[str]] = ["query", "limit", "time", "location", "source", "category", "includeDomains", "excludeDomains", "format", "scrape", "scrapeLimit", "groundedAnswer"]

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['web', 'news', 'images']):
            raise ValueError("must be one of enum values ('web', 'news', 'images')")
        return value

    @field_validator('category')
    def category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['general', 'code', 'pdf', 'research', 'linkedin', 'wiki']):
            raise ValueError("must be one of enum values ('general', 'code', 'pdf', 'research', 'linkedin', 'wiki')")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['json', 'markdown', 'html']):
            raise ValueError("must be one of enum values ('json', 'markdown', 'html')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "limit": obj.get("limit") if obj.get("limit") is not None else 10,
            "time": obj.get("time") if obj.get("time") is not None else 'any',
            "location": obj.get("location") if obj.get("location") is not None else 'us',
            "source": obj.get("source") if obj.get("source") is not None else 'web',
            "category": obj.get("category") if obj.get("category") is not None else 'general',
            "includeDomains": obj.get("includeDomains"),
            "excludeDomains": obj.get("excludeDomains"),
            "format": obj.get("format") if obj.get("format") is not None else 'json',
            "scrape": obj.get("scrape") if obj.get("scrape") is not None else False,
            "scrapeLimit": obj.get("scrapeLimit") if obj.get("scrapeLimit") is not None else 3,
            "groundedAnswer": obj.get("groundedAnswer") if obj.get("groundedAnswer") is not None else False
        })
        return _obj


