# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from geekflare_api.models.search_serp_data_dto_ai_overview_references_inner import SearchSerpDataDtoAiOverviewReferencesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchSerpDataDtoAiOverview(BaseModel):
    """
    AI Overview that Google shows for the query. Only present when Google returns one.
    """ # noqa: E501
    text: Optional[StrictStr] = Field(default=None, description="AI Overview as plain text")
    html: Optional[StrictStr] = Field(default=None, description="AI Overview as the raw HTML Google rendered")
    references: Optional[List[SearchSerpDataDtoAiOverviewReferencesInner]] = Field(default=None, description="Sources cited by the AI Overview")
    __properties: ClassVar[List[str]] = ["text", "html", "references"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoAiOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in references (list)
        _items = []
        if self.references:
            for _item_references in self.references:
                if _item_references:
                    _items.append(_item_references.to_dict())
            _dict['references'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSerpDataDtoAiOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "html": obj.get("html"),
            "references": [SearchSerpDataDtoAiOverviewReferencesInner.from_dict(_item) for _item in obj["references"]] if obj.get("references") is not None else None
        })
        return _obj


