# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from geekflare_api.models.search_serp_data_dto_ai_overview import SearchSerpDataDtoAiOverview
from geekflare_api.models.search_serp_data_dto_general import SearchSerpDataDtoGeneral
from geekflare_api.models.search_serp_data_dto_input import SearchSerpDataDtoInput
from geekflare_api.models.search_serp_data_dto_navigation_inner import SearchSerpDataDtoNavigationInner
from geekflare_api.models.search_serp_data_dto_organic_inner import SearchSerpDataDtoOrganicInner
from geekflare_api.models.search_serp_data_dto_pagination import SearchSerpDataDtoPagination
from geekflare_api.models.search_serp_data_dto_people_also_ask_inner import SearchSerpDataDtoPeopleAlsoAskInner
from geekflare_api.models.search_serp_data_dto_related_inner import SearchSerpDataDtoRelatedInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchSerpDataDto(BaseModel):
    """
    Full Google SERP. Which sections are present depends on what Google returns for the query. With `source` set to `news` or `images`, results are returned under `news` or `images` instead of `organic`.
    """ # noqa: E501
    general: Optional[SearchSerpDataDtoGeneral] = None
    input: Optional[SearchSerpDataDtoInput] = None
    navigation: Optional[List[SearchSerpDataDtoNavigationInner]] = Field(default=None, description="Search vertical tabs shown on the page (Images, News, Videos, Maps, etc.)")
    organic: Optional[List[SearchSerpDataDtoOrganicInner]] = Field(default=None, description="Organic (non-ad) results")
    news: Optional[List[Dict[str, Any]]] = Field(default=None, description="News results. Returned instead of `organic` when `source` is `news`.")
    images: Optional[List[Dict[str, Any]]] = Field(default=None, description="Image results. Returned instead of `organic` when `source` is `images`.")
    pagination: Optional[SearchSerpDataDtoPagination] = None
    related: Optional[List[SearchSerpDataDtoRelatedInner]] = Field(default=None, description="Related searches")
    ai_overview: Optional[SearchSerpDataDtoAiOverview] = None
    people_also_ask: Optional[List[SearchSerpDataDtoPeopleAlsoAskInner]] = Field(default=None, description="People Also Ask questions")
    __properties: ClassVar[List[str]] = ["general", "input", "navigation", "organic", "news", "images", "pagination", "related", "ai_overview", "people_also_ask"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSerpDataDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of general
        if self.general:
            _dict['general'] = self.general.to_dict()
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in navigation (list)
        _items = []
        if self.navigation:
            for _item_navigation in self.navigation:
                if _item_navigation:
                    _items.append(_item_navigation.to_dict())
            _dict['navigation'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in organic (list)
        _items = []
        if self.organic:
            for _item_organic in self.organic:
                if _item_organic:
                    _items.append(_item_organic.to_dict())
            _dict['organic'] = _items
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related (list)
        _items = []
        if self.related:
            for _item_related in self.related:
                if _item_related:
                    _items.append(_item_related.to_dict())
            _dict['related'] = _items
        # override the default output from pydantic by calling `to_dict()` of ai_overview
        if self.ai_overview:
            _dict['ai_overview'] = self.ai_overview.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in people_also_ask (list)
        _items = []
        if self.people_also_ask:
            for _item_people_also_ask in self.people_also_ask:
                if _item_people_also_ask:
                    _items.append(_item_people_also_ask.to_dict())
            _dict['people_also_ask'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSerpDataDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "general": SearchSerpDataDtoGeneral.from_dict(obj["general"]) if obj.get("general") is not None else None,
            "input": SearchSerpDataDtoInput.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "navigation": [SearchSerpDataDtoNavigationInner.from_dict(_item) for _item in obj["navigation"]] if obj.get("navigation") is not None else None,
            "organic": [SearchSerpDataDtoOrganicInner.from_dict(_item) for _item in obj["organic"]] if obj.get("organic") is not None else None,
            "news": obj.get("news"),
            "images": obj.get("images"),
            "pagination": SearchSerpDataDtoPagination.from_dict(obj["pagination"]) if obj.get("pagination") is not None else None,
            "related": [SearchSerpDataDtoRelatedInner.from_dict(_item) for _item in obj["related"]] if obj.get("related") is not None else None,
            "ai_overview": SearchSerpDataDtoAiOverview.from_dict(obj["ai_overview"]) if obj.get("ai_overview") is not None else None,
            "people_also_ask": [SearchSerpDataDtoPeopleAlsoAskInner.from_dict(_item) for _item in obj["people_also_ask"]] if obj.get("people_also_ask") is not None else None
        })
        return _obj


