# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TlsForwardSecrecyDto(BaseModel):
    """
    TlsForwardSecrecyDto
    """ # noqa: E501
    negotiated_cipher: Dict[str, Any] = Field(description="Cipher suite negotiated on the primary handshake", alias="negotiatedCipher")
    ephemeral_key_type: Dict[str, Any] = Field(description="Ephemeral key exchange type (e.g. ECDH, DH), null if the cipher does not provide forward secrecy", alias="ephemeralKeyType")
    ephemeral_key_size: Dict[str, Any] = Field(description="Ephemeral key size in bits", alias="ephemeralKeySize")
    __properties: ClassVar[List[str]] = ["negotiatedCipher", "ephemeralKeyType", "ephemeralKeySize"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TlsForwardSecrecyDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TlsForwardSecrecyDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "negotiatedCipher": obj.get("negotiatedCipher"),
            "ephemeralKeyType": obj.get("ephemeralKeyType"),
            "ephemeralKeySize": obj.get("ephemeralKeySize")
        })
        return _obj


