# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from geekflare_api.models.tls_certificate_chain_dto import TlsCertificateChainDto
from geekflare_api.models.tls_certificate_issuer_dto import TlsCertificateIssuerDto
from geekflare_api.models.tls_forward_secrecy_dto import TlsForwardSecrecyDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TlsCertificateDto(BaseModel):
    """
    TlsCertificateDto
    """ # noqa: E501
    common_name: StrictStr = Field(description="Common name (CN) on the certificate", alias="commonName", json_schema_extra={"examples": ["sni.cloudflaressl.com"]})
    subject_alt_name: StrictStr = Field(description="Subject Alternative Names (SAN)", alias="subjectAltName", json_schema_extra={"examples": ["DNS:*.example.com, DNS:sni.cloudflaressl.com, DNS:example.com"]})
    issuer: TlsCertificateIssuerDto = Field(description="Issuer details")
    expiry: StrictStr = Field(description="Certificate expiry date", json_schema_extra={"examples": ["Jun  6 23:59:59 2023 GMT"]})
    valid_from: StrictStr = Field(description="Certificate valid-from date", alias="validFrom")
    is_expired: StrictBool = Field(description="Whether the certificate has expired", alias="isExpired")
    is_not_yet_valid: StrictBool = Field(description="Whether the certificate is not yet valid", alias="isNotYetValid")
    hostname_matches: StrictBool = Field(description="Whether the requested hostname matches the certificate (CN/SAN)", alias="hostnameMatches")
    self_signed: StrictBool = Field(description="Whether the leaf certificate is self-signed", alias="selfSigned")
    key_bits: Dict[str, Any] = Field(description="Public key size in bits, null if not an RSA key", alias="keyBits")
    weak_key: Dict[str, Any] = Field(description="Whether the key size is considered weak (RSA < 2048 bits), null if not applicable", alias="weakKey")
    weak_signature_algorithm: Dict[str, Any] = Field(description="Whether the certificate uses a weak signature algorithm (SHA-1/MD5); heuristic OID scan, null if undeterminable", alias="weakSignatureAlgorithm")
    chain: TlsCertificateChainDto = Field(description="Certificate chain analysis")
    forward_secrecy: TlsForwardSecrecyDto = Field(description="Forward secrecy signal from the negotiated handshake", alias="forwardSecrecy")
    trusted: StrictBool = Field(description="Whether the chain validates against Node/OpenSSL's built-in trust store")
    authorization_error: Dict[str, Any] = Field(description="Node TLS authorization error code/message if not trusted, null otherwise", alias="authorizationError")
    __properties: ClassVar[List[str]] = ["commonName", "subjectAltName", "issuer", "expiry", "validFrom", "isExpired", "isNotYetValid", "hostnameMatches", "selfSigned", "keyBits", "weakKey", "weakSignatureAlgorithm", "chain", "forwardSecrecy", "trusted", "authorizationError"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TlsCertificateDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of issuer
        if self.issuer:
            _dict['issuer'] = self.issuer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chain
        if self.chain:
            _dict['chain'] = self.chain.to_dict()
        # override the default output from pydantic by calling `to_dict()` of forward_secrecy
        if self.forward_secrecy:
            _dict['forwardSecrecy'] = self.forward_secrecy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TlsCertificateDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commonName": obj.get("commonName"),
            "subjectAltName": obj.get("subjectAltName"),
            "issuer": TlsCertificateIssuerDto.from_dict(obj["issuer"]) if obj.get("issuer") is not None else None,
            "expiry": obj.get("expiry"),
            "validFrom": obj.get("validFrom"),
            "isExpired": obj.get("isExpired"),
            "isNotYetValid": obj.get("isNotYetValid"),
            "hostnameMatches": obj.get("hostnameMatches"),
            "selfSigned": obj.get("selfSigned"),
            "keyBits": obj.get("keyBits"),
            "weakKey": obj.get("weakKey"),
            "weakSignatureAlgorithm": obj.get("weakSignatureAlgorithm"),
            "chain": TlsCertificateChainDto.from_dict(obj["chain"]) if obj.get("chain") is not None else None,
            "forwardSecrecy": TlsForwardSecrecyDto.from_dict(obj["forwardSecrecy"]) if obj.get("forwardSecrecy") is not None else None,
            "trusted": obj.get("trusted"),
            "authorizationError": obj.get("authorizationError")
        })
        return _obj


