# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from geekflare_api.models.tls_certificate_chain_entry_dto import TlsCertificateChainEntryDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TlsCertificateChainDto(BaseModel):
    """
    TlsCertificateChainDto
    """ # noqa: E501
    length: Union[StrictFloat, StrictInt] = Field(description="Number of certificates in the chain as presented by the server")
    complete: StrictBool = Field(description="Whether the chain terminates in a self-signed root (i.e. is not missing an intermediate)")
    certificates: List[TlsCertificateChainEntryDto] = Field(description="Ordered list of certificates from leaf to root")
    __properties: ClassVar[List[str]] = ["length", "complete", "certificates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TlsCertificateChainDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in certificates (list)
        _items = []
        if self.certificates:
            for _item_certificates in self.certificates:
                if _item_certificates:
                    _items.append(_item_certificates.to_dict())
            _dict['certificates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TlsCertificateChainDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "length": obj.get("length"),
            "complete": obj.get("complete"),
            "certificates": [TlsCertificateChainEntryDto.from_dict(_item) for _item in obj["certificates"]] if obj.get("certificates") is not None else None
        })
        return _obj


