# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.margin_dto import MarginDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Url2PdfDto(BaseModel):
    """
    Url2PdfDto
    """ # noqa: E501
    url: StrictStr = Field(description="Target URL", json_schema_extra={"examples": ["https://example.com"]})
    device: Optional[StrictStr] = Field(default='desktop', description="Device type to emulate. Defaults to desktop.", json_schema_extra={"examples": ["desktop"]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country code to route the request", alias="proxyCountry", json_schema_extra={"examples": ["us"]})
    format: Optional[StrictStr] = Field(default='a4', description="Paper format", json_schema_extra={"examples": ["a4"]})
    orientation: Optional[StrictStr] = Field(default='portrait', description="Orientation", json_schema_extra={"examples": ["portrait"]})
    margin: Optional[MarginDto] = Field(default=None, description="Margins in mm")
    scale: Optional[Union[StrictFloat, StrictInt]] = Field(default=1, description="Rendering scale between 0–2", json_schema_extra={"examples": [1.5]})
    hide_cookie: Optional[StrictBool] = Field(default=False, description="Hide cookie popups", alias="hideCookie", json_schema_extra={"examples": [False]})
    skip_captcha: Optional[StrictBool] = Field(default=False, description="Try to skip captcha", alias="skipCaptcha", json_schema_extra={"examples": [False]})
    add_timestamp: Optional[StrictBool] = Field(default=False, description="Add timestamp watermark", alias="addTimestamp", json_schema_extra={"examples": [False]})
    __properties: ClassVar[List[str]] = ["url", "device", "proxyCountry", "format", "orientation", "margin", "scale", "hideCookie", "skipCaptcha", "addTimestamp"]

    @field_validator('device')
    def device_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['desktop', 'mobile']):
            raise ValueError("must be one of enum values ('desktop', 'mobile')")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['letter', 'legal', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6']):
            raise ValueError("must be one of enum values ('letter', 'legal', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6')")
        return value

    @field_validator('orientation')
    def orientation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['portrait', 'landscape']):
            raise ValueError("must be one of enum values ('portrait', 'landscape')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Url2PdfDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of margin
        if self.margin:
            _dict['margin'] = self.margin.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Url2PdfDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "device": obj.get("device") if obj.get("device") is not None else 'desktop',
            "proxyCountry": obj.get("proxyCountry"),
            "format": obj.get("format") if obj.get("format") is not None else 'a4',
            "orientation": obj.get("orientation") if obj.get("orientation") is not None else 'portrait',
            "margin": MarginDto.from_dict(obj["margin"]) if obj.get("margin") is not None else None,
            "scale": obj.get("scale") if obj.get("scale") is not None else 1,
            "hideCookie": obj.get("hideCookie") if obj.get("hideCookie") is not None else False,
            "skipCaptcha": obj.get("skipCaptcha") if obj.get("skipCaptcha") is not None else False,
            "addTimestamp": obj.get("addTimestamp") if obj.get("addTimestamp") is not None else False
        })
        return _obj


