# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.margin_dto import MarginDto
from geekflare_api.models.test_meta_dto import TestMetaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Url2PdfMetaDto(BaseModel):
    """
    Url2PdfMetaDto
    """ # noqa: E501
    url: StrictStr = Field(description="The target URL", json_schema_extra={"examples": ["https://example.com"]})
    device: StrictStr = Field(description="Device type used", json_schema_extra={"examples": ["desktop"]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country used, if any", alias="proxyCountry")
    format: StrictStr = Field(description="Paper format", json_schema_extra={"examples": ["letter"]})
    orientation: StrictStr = Field(description="Orientation", json_schema_extra={"examples": ["landscape"]})
    margin: Optional[MarginDto] = Field(default=None, description="Margins in mm")
    scale: Union[StrictFloat, StrictInt] = Field(description="Rendering scale", json_schema_extra={"examples": [1.5]})
    test: TestMetaDto = Field(description="Test details")
    __properties: ClassVar[List[str]] = ["url", "device", "proxyCountry", "format", "orientation", "margin", "scale", "test"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Url2PdfMetaDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of margin
        if self.margin:
            _dict['margin'] = self.margin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test
        if self.test:
            _dict['test'] = self.test.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Url2PdfMetaDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "device": obj.get("device"),
            "proxyCountry": obj.get("proxyCountry"),
            "format": obj.get("format"),
            "orientation": obj.get("orientation"),
            "margin": MarginDto.from_dict(obj["margin"]) if obj.get("margin") is not None else None,
            "scale": obj.get("scale"),
            "test": TestMetaDto.from_dict(obj["test"]) if obj.get("test") is not None else None
        })
        return _obj


