# coding: utf-8

"""
    Geekflare API

    Official OpenAPI specification for all Geekflare API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from geekflare_api.models.extraction_schema_dto import ExtractionSchemaDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WebScrapeDto(BaseModel):
    """
    WebScrapeDto
    """ # noqa: E501
    url: StrictStr = Field(description="Target URL", json_schema_extra={"examples": ["https://example.com"]})
    device: Optional[StrictStr] = Field(default='desktop', description="Device type to emulate. Defaults to desktop.", json_schema_extra={"examples": ["desktop"]})
    block_ads: Optional[StrictBool] = Field(default=True, description="Whether to block ads", alias="blockAds", json_schema_extra={"examples": [True]})
    render_js: Optional[StrictBool] = Field(default=True, description="Whether to render JavaScript", alias="renderJS", json_schema_extra={"examples": [True]})
    proxy_country: Optional[StrictStr] = Field(default=None, description="Proxy country code to route the request", alias="proxyCountry", json_schema_extra={"examples": ["us"]})
    format: Optional[List[StrictStr]] = Field(default=None, description="Format(s) of the scraped result. Comma-separated or array. Defaults to html.", json_schema_extra={"examples": ["html,markdown"]})
    file_output: Optional[StrictBool] = Field(default=False, description="Whether to get response in file format", alias="fileOutput", json_schema_extra={"examples": [False]})
    stealth: Optional[StrictBool] = Field(default=False, description="Enable stealth mode to bypass basic bot detection (removes webdriver signals, patches navigator properties)", json_schema_extra={"examples": [False]})
    wait_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, description="Seconds to wait after page load before capturing content. Helps bypass lazy-loaded content and bot checks.", alias="waitTime", json_schema_extra={"examples": [2.5]})
    extraction_mode: Optional[StrictStr] = Field(default='default', description="Extraction mode (only used if format=json)", alias="extractionMode", json_schema_extra={"examples": ["default"]})
    extraction_schema: Optional[ExtractionSchemaDto] = Field(default=None, description="Extraction schema (optional in default mode, required in css/xpath)", alias="extractionSchema")
    __properties: ClassVar[List[str]] = ["url", "device", "blockAds", "renderJS", "proxyCountry", "format", "fileOutput", "stealth", "waitTime", "extractionMode", "extractionSchema"]

    @field_validator('device')
    def device_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['desktop', 'mobile']):
            raise ValueError("must be one of enum values ('desktop', 'mobile')")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['html', 'markdown', 'json', 'markdown-llm', 'html-llm', 'text', 'text-llm']):
                raise ValueError("each list item must be one of ('html', 'markdown', 'json', 'markdown-llm', 'html-llm', 'text', 'text-llm')")
        return value

    @field_validator('extraction_mode')
    def extraction_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default', 'cssSchema', 'xpathSchema']):
            raise ValueError("must be one of enum values ('default', 'cssSchema', 'xpathSchema')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebScrapeDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of extraction_schema
        if self.extraction_schema:
            _dict['extractionSchema'] = self.extraction_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebScrapeDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "device": obj.get("device") if obj.get("device") is not None else 'desktop',
            "blockAds": obj.get("blockAds") if obj.get("blockAds") is not None else True,
            "renderJS": obj.get("renderJS") if obj.get("renderJS") is not None else True,
            "proxyCountry": obj.get("proxyCountry"),
            "format": obj.get("format"),
            "fileOutput": obj.get("fileOutput") if obj.get("fileOutput") is not None else False,
            "stealth": obj.get("stealth") if obj.get("stealth") is not None else False,
            "waitTime": obj.get("waitTime") if obj.get("waitTime") is not None else 0,
            "extractionMode": obj.get("extractionMode") if obj.get("extractionMode") is not None else 'default',
            "extractionSchema": ExtractionSchemaDto.from_dict(obj["extractionSchema"]) if obj.get("extractionSchema") is not None else None
        })
        return _obj


