# coding: utf-8

"""
    Geekflare

    Official OpenAPI specification for all Geekflare endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from geekflare_api.models.keywords_ai_prompt_dto import KeywordsAiPromptDto
from geekflare_api.models.listing_ai_prompt_dto import ListingAiPromptDto
from geekflare_api.models.prompt_ai_prompt_dto import PromptAiPromptDto
from geekflare_api.models.schema_ai_prompt_dto import SchemaAiPromptDto
from geekflare_api.models.sentiment_ai_prompt_dto import SentimentAiPromptDto
from geekflare_api.models.summary_ai_prompt_dto import SummaryAiPromptDto
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

WEBSCRAPEDTOAIPROMPT_ONE_OF_SCHEMAS = ["KeywordsAiPromptDto", "ListingAiPromptDto", "PromptAiPromptDto", "SchemaAiPromptDto", "SentimentAiPromptDto", "SummaryAiPromptDto"]

class WebScrapeDtoAiPrompt(BaseModel):
    """
    Ask AI to extract or analyze the scraped page. Always runs against the Markdown of the page regardless of the format field. Adds +7 credits on top of the base scraping cost.
    """
    # data type: PromptAiPromptDto
    oneof_schema_1_validator: Optional[PromptAiPromptDto] = None
    # data type: SchemaAiPromptDto
    oneof_schema_2_validator: Optional[SchemaAiPromptDto] = None
    # data type: ListingAiPromptDto
    oneof_schema_3_validator: Optional[ListingAiPromptDto] = None
    # data type: SummaryAiPromptDto
    oneof_schema_4_validator: Optional[SummaryAiPromptDto] = None
    # data type: SentimentAiPromptDto
    oneof_schema_5_validator: Optional[SentimentAiPromptDto] = None
    # data type: KeywordsAiPromptDto
    oneof_schema_6_validator: Optional[KeywordsAiPromptDto] = None
    actual_instance: Optional[Union[KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto]] = None
    one_of_schemas: Set[str] = { "KeywordsAiPromptDto", "ListingAiPromptDto", "PromptAiPromptDto", "SchemaAiPromptDto", "SentimentAiPromptDto", "SummaryAiPromptDto" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WebScrapeDtoAiPrompt.model_construct()
        error_messages = []
        match = 0
        # validate data type: PromptAiPromptDto
        if not isinstance(v, PromptAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PromptAiPromptDto`")
        else:
            match += 1
        # validate data type: SchemaAiPromptDto
        if not isinstance(v, SchemaAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SchemaAiPromptDto`")
        else:
            match += 1
        # validate data type: ListingAiPromptDto
        if not isinstance(v, ListingAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListingAiPromptDto`")
        else:
            match += 1
        # validate data type: SummaryAiPromptDto
        if not isinstance(v, SummaryAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SummaryAiPromptDto`")
        else:
            match += 1
        # validate data type: SentimentAiPromptDto
        if not isinstance(v, SentimentAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SentimentAiPromptDto`")
        else:
            match += 1
        # validate data type: KeywordsAiPromptDto
        if not isinstance(v, KeywordsAiPromptDto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `KeywordsAiPromptDto`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WebScrapeDtoAiPrompt with oneOf schemas: KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WebScrapeDtoAiPrompt with oneOf schemas: KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PromptAiPromptDto
        try:
            instance.actual_instance = PromptAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SchemaAiPromptDto
        try:
            instance.actual_instance = SchemaAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ListingAiPromptDto
        try:
            instance.actual_instance = ListingAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SummaryAiPromptDto
        try:
            instance.actual_instance = SummaryAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SentimentAiPromptDto
        try:
            instance.actual_instance = SentimentAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into KeywordsAiPromptDto
        try:
            instance.actual_instance = KeywordsAiPromptDto.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WebScrapeDtoAiPrompt with oneOf schemas: KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WebScrapeDtoAiPrompt with oneOf schemas: KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], KeywordsAiPromptDto, ListingAiPromptDto, PromptAiPromptDto, SchemaAiPromptDto, SentimentAiPromptDto, SummaryAiPromptDto]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


